const initSqlJs = require('sql.js');
const fs = require('fs');
const SQL = await initSqlJs({ wasmBinary: fs.readFileSync('node_modules/sql.js/dist/sql-wasm.wasm') });
const load = (p) => JSON.parse(fs.readFileSync(p, 'utf8').match(/export const \w+ = (".*");\n/s)[1]);
const adv = new SQL.Database(); adv.exec(load('src/content/datasets/advanced.ts'));
const q = (sql) => { const r = adv.exec(sql); return r.length ? r[0].values : []; };
console.log('adv VIPs:', q("SELECT COUNT(*) FROM customers WHERE customer_type='vip'"));
console.log('adv payment 3 amount:', q('SELECT amount FROM payments WHERE id = 3'));
console.log('adv payment 10 amount:', q('SELECT amount FROM payments WHERE id = 10'));
console.log('adv product price stats:', q('SELECT MIN(price), MAX(price), ROUND(AVG(price),2) FROM products'));
console.log('adv top product:', JSON.stringify(q('SELECT name, price FROM products ORDER BY price DESC, id LIMIT 3')));
console.log('adv upi count:', q("SELECT COUNT(*) FROM payments WHERE payment_method='upi'"));
console.log('adv EXPLAIN ORDER BY name:', JSON.stringify(adv.exec('EXPLAIN QUERY PLAN SELECT * FROM customers ORDER BY name')));
console.log('adv monthly jan feb:', JSON.stringify(q("SELECT substr(o.order_date,1,7), ROUND(SUM(p.amount),2) FROM orders o JOIN payments p ON p.order_id=o.id GROUP BY 1 ORDER BY 1 LIMIT 2")));
console.log('adv cat count:', q('SELECT COUNT(*) FROM categories'));
console.log('adv orders per cust first2:', JSON.stringify(q('SELECT name, (SELECT COUNT(*) FROM orders o WHERE o.customer_id=c.id) FROM customers c ORDER BY id LIMIT 2')));
console.log('eco above avg spend count:');
const eco = new SQL.Database(); eco.exec(load('src/content/datasets/ecommerce.ts'));
const qe = (sql) => { const r = eco.exec(sql); return r.length ? r[0].values : []; };
console.log(qe('SELECT COUNT(*) FROM (SELECT o.customer_id, SUM(p.amount) s FROM payments p JOIN orders o ON o.id=p.order_id GROUP BY o.customer_id) WHERE s > (SELECT AVG(s) FROM (SELECT SUM(p.amount) s FROM payments p JOIN orders o ON o.id=p.order_id GROUP BY o.customer_id))'));
