const initSqlJs = require('sql.js');
const fs = require('fs');
const SQL = await initSqlJs({ wasmBinary: fs.readFileSync('node_modules/sql.js/dist/sql-wasm.wasm') });
const load = (p) => JSON.parse(fs.readFileSync(p, 'utf8').match(/export const \w+ = (".*");\n/s)[1]);
const eco = new SQL.Database(); eco.exec(load('src/content/datasets/ecommerce.ts'));
const adv = new SQL.Database(); adv.exec(load('src/content/datasets/advanced.ts'));
const q = (db, sql) => { const r = db.exec(sql); return r.length ? r[0].values : []; };
console.log('=== ECOMMERCE ===');
console.log('sum payments:', q(eco, 'SELECT ROUND(SUM(amount),2), ROUND(AVG(amount),2) FROM payments'));
console.log('cust w delivered:', q(eco, "SELECT COUNT(DISTINCT customer_id) FROM orders WHERE status='delivered'"));
console.log('delivered orders:', q(eco, "SELECT COUNT(*) FROM orders WHERE status='delivered'"));
console.log('first 2 cust orders:', JSON.stringify(q(eco, 'SELECT name, (SELECT COUNT(*) FROM orders o WHERE o.customer_id=c.id) FROM customers c ORDER BY id LIMIT 2')));
console.log('top 3 products:', JSON.stringify(q(eco, 'SELECT name, price FROM products ORDER BY price DESC LIMIT 3')));
console.log('priciest per cat sample:', JSON.stringify(q(eco, "SELECT name FROM products WHERE category_id=2 ORDER BY price DESC LIMIT 3")));
console.log('cities >6:', JSON.stringify(q(eco, 'SELECT city, COUNT(*) FROM customers GROUP BY city HAVING COUNT(*) > 6 ORDER BY COUNT(*) DESC')));
console.log('age NOT between:', q(eco, 'SELECT 1'));
console.log('top 3 oldest students? eco has none');
console.log('=== SCHOOL ===');
const school = new SQL.Database(); school.exec(load('src/content/datasets/school.ts'));
console.log('delhiMumbai gradeA:', q(school, "SELECT COUNT(*) FROM students WHERE (city='Delhi' OR city='Mumbai') AND grade='A'"));
console.log('age NOT 17-19:', q(school, 'SELECT COUNT(*) FROM students WHERE age NOT BETWEEN 17 AND 19'));
console.log('oldest 3:', JSON.stringify(q(school, 'SELECT name, age FROM students ORDER BY age DESC, name LIMIT 3')));
console.log('=== ADVANCED ===');
console.log('sum payments:', q(adv, 'SELECT ROUND(SUM(amount),2), ROUND(AVG(amount),2) FROM payments'));
console.log('cust w delivered:', q(adv, "SELECT COUNT(DISTINCT customer_id) FROM orders WHERE status='delivered'"));
console.log('delivered orders:', q(adv, "SELECT COUNT(*) FROM orders WHERE status='delivered'"));
console.log('top spenders:', JSON.stringify(q(adv, 'SELECT c.name, ROUND(SUM(p.amount),2) FROM customers c JOIN orders o ON o.customer_id=c.id JOIN payments p ON p.order_id=o.id GROUP BY c.id ORDER BY SUM(p.amount) DESC LIMIT 3')));
console.log('spend >1M:', q(adv, 'SELECT COUNT(*) FROM (SELECT o.customer_id, SUM(p.amount) s FROM payments p JOIN orders o ON o.id=p.order_id GROUP BY o.customer_id) WHERE s>1000000'));
console.log('M30 t6 above-avg count:', q(adv, 'SELECT COUNT(*) FROM (SELECT o.customer_id, SUM(p.amount) s FROM payments p JOIN orders o ON o.id=p.order_id GROUP BY o.customer_id) WHERE s > (SELECT AVG(s) FROM (SELECT SUM(p.amount) s FROM payments p JOIN orders o ON o.id=p.order_id GROUP BY o.customer_id))'));
console.log('rev by status:', JSON.stringify(q(adv, "SELECT o.status, COUNT(*), ROUND(SUM(p.amount),2) FROM orders o JOIN payments p ON p.order_id=o.id GROUP BY o.status ORDER BY COUNT(*) DESC")));
console.log('monthly 6:', JSON.stringify(q(adv, "SELECT substr(o.order_date,1,7), ROUND(SUM(p.amount),2) FROM orders o JOIN payments p ON p.order_id=o.id GROUP BY 1 ORDER BY 1 LIMIT 2")));
