/** Generate curriculum index + verify all modules load. Run: bun scripts/gen-index.ts */
import { MODULE_BODIES } from '../src/content/modules/registry';
import fs from 'fs';
import path from 'path';

const entries: string[] = [];
const problems: string[] = [];

const sorted = [...MODULE_BODIES].sort((a, b) => a.number - b.number);

// Spec task counts: regular modules 5; project modules per spec §14
const TASK_COUNTS: Record<number, number> = { 10: 5, 20: 8, 30: 6, 40: 10, 49: 6, 59: 4, 60: 12 };
// Completeness checks
for (let n = 1; n <= 60; n++) {
  const m = sorted.find((x) => x.number === n);
  if (!m) { problems.push(`MISSING module ${n}`); continue; }
  const want = TASK_COUNTS[n] ?? 5;
  if (m.tasks.length !== want) problems.push(`M${n}: has ${m.tasks.length} tasks (want ${want})`);
  if (m.quiz.length !== 4) problems.push(`M${n}: has ${m.quiz.length} quiz questions (want 4)`);
  for (const t of m.tasks) {
    if (t.hints.length !== 3) problems.push(`M${n}.${t.id}: ${t.hints.length} hints`);
    for (const h of t.hints) {
      if (!h.content.en || !h.content.hi) problems.push(`M${n}.${t.id} hint L${h.level}: missing language`);
    }
    if (!t.solution?.trim()) problems.push(`M${n}.${t.id}: empty solution`);
  }
  entries.push(`  ${n}: { id: '${m.id}', number: ${m.number}, level: '${m.level}', dataset: '${m.dataset}', titleEn: ${JSON.stringify(m.title.en)}, titleHi: ${JSON.stringify(m.title.hi)}, concepts: ${JSON.stringify(m.concepts)}, taskCount: ${m.tasks.length}, hasQuiz: ${m.quiz.length === 4}, estimatedTime: ${JSON.stringify(m.estimatedTime)} },`);
}

const out = `// AUTO-GENERATED by scripts/gen-index.ts — do not edit by hand
import type { ModuleIndexEntry } from '@/lib/content/registry';

export const CURRICULUM_INDEX: Record<number, ModuleIndexEntry> = {
${entries.join('\n')}
};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'content', 'modules', 'index.ts'), out);
console.log('index.ts written with', entries.length, 'entries');

if (problems.length) {
  console.log('\nPROBLEMS:');
  for (const p of problems) console.log(' ✗', p);
  process.exit(1);
}
console.log('ALL CONTENT STRUCTURE CHECKS PASSED');
