'use client';

// ============ 10 Projects (spec §14): 6 mini + 3 level + 1 capstone ============

import type { Project, ProjectTask } from '@/types/content';
import { h3 } from '@/content/modules/builder';

type L = [string, string];
const t = (
  id: string,
  difficulty: ProjectTask['difficulty'],
  ctx: L,
  desc: L,
  sol: string,
  verify: string | undefined,
  hints: [L, L, L],
  rules?: ProjectTask['validation'],
): ProjectTask => ({
  id,
  difficulty,
  businessContext: { en: ctx[0], hi: ctx[1] },
  taskDescription: { en: desc[0], hi: desc[1] },
  solution: sol,
  verifyQuery: verify,
  hints: h3(hints[0], hints[1], hints[2]),
  validation: rules ?? {},
});

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    kind: 'mini',
    moduleNumber: 10,
    order: 1,
    title: { en: 'Student Directory Queries', hi: 'Student Directory Queries' },
    subtitle: { en: 'Five front-office requests on the school database', hi: 'School database par paanch front-office requests' },
    dataset: 'school',
    intro: {
      en: 'The school front office is assembling a printed student directory. Five departments have sent data requests — each answered with one precise query combining projection, filtering, aliases, DISTINCT and sorting exactly as asked.',
      hi: 'School front office print hone wali student directory taiyar kar rahi hai. Paanch departments ne data requests bheji hain — har ek ek precise query se jawaab, jisme projection, filtering, aliases, DISTINCT aur sorting bilkul maange gaye tareeke se jude hain.',
    },
    skillsTested: ['SELECT', 'WHERE', 'aliases', 'DISTINCT', 'ORDER BY'],
    estimatedTime: '20 min',
    tasks: [
      t('task-1', 'easy',
        ['The registrar wants accurate labels for the printed directory.', 'Registrar ko printed directory ke liye sahi labels chahiye.'],
        ['Show each student\'s name and city with the headers student and hometown.', 'Har student ka naam aur city dikhao, headers student aur hometown ke saath.'],
        'SELECT name AS student, city AS hometown FROM students;',
        undefined,
        [['Two columns, two aliases.', 'Do columns, do aliases.'],
         ['SELECT name AS student, city AS hometown FROM students;', 'SELECT name AS student, city AS hometown FROM students;'],
         ['Headers are checked in this task.', 'Is task me headers check hote hain.']],
        { checkColumnNames: true },
      ),
      t('task-2', 'easy',
        ['The counselling office follows struggling students through the term.', 'Counselling office term bhar mushkil wale students ko follow karti hai.'],
        ['List the names of grade-F students, sorted alphabetically.', 'Grade-F students ke naam list karo, alphabetically sorted.'],
        "SELECT name FROM students WHERE grade = 'F' ORDER BY name;",
        undefined,
        [['One equality filter on text, one sort.', 'Text par ek equality filter, ek sort.'],
         ["SELECT name FROM students WHERE grade = 'F' ORDER BY name;", "SELECT name FROM students WHERE grade = 'F' ORDER BY name;"],
         ['Nine names appear.', 'Nau naam dikhte hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-3', 'medium',
        ['The transport office needs the coverage-map page.', 'Transport office ko coverage-map page chahiye.'],
        ['Show each city that has at least one student, each once, with the header city.', 'Har wo city dikhao jahan kam se kam ek student hai, har ek ek baar, header city ke saath.'],
        'SELECT DISTINCT city AS city FROM students;',
        undefined,
        [['DISTINCT deduplicates the projection.', 'DISTINCT projection deduplicate karta hai.'],
         ['SELECT DISTINCT city FROM students;', 'SELECT DISTINCT city FROM students;'],
         ['Ten unique cities.', 'Das unique cities.']],
        { checkColumnNames: true },
      ),
      t('task-4', 'medium',
        ['The scholarship committee reviews adult merit students.', 'Scholarship committee bade merit students review karti hai.'],
        ['Show name, grade and age for grade-A students who are 18 or older, sorted by name.', 'Grade-A aur 18-ya-bade students ka naam, grade aur age dikhao, naam se sorted.'],
        "SELECT name, grade, age FROM students WHERE grade = 'A' AND age >= 18 ORDER BY name;",
        undefined,
        [['Two required conditions joined with AND.', 'AND se judi do zaroori conditions.'],
         ["SELECT name, grade, age FROM students WHERE grade = 'A' AND age >= 18 ORDER BY name;", "SELECT name, grade, age FROM students WHERE grade = 'A' AND age >= 18 ORDER BY name;"],
         ['A handful of students qualify.', 'Chand students qualify karte hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-5', 'hard',
        ['The principal wants the cover-page stats card.', 'Principal cover-page stats card chahta hai.'],
        ['One row with three numbers: total students (students), unique hometowns (hometowns), students with email (with_email). Headers checked.', 'Ek row me teen numbers: kul students (students), unique hometowns (hometowns), email wale students (with_email). Headers check honge.'],
        'SELECT COUNT(*) AS students, COUNT(DISTINCT city) AS hometowns, COUNT(email) AS with_email FROM students;',
        undefined,
        [['Three COUNT flavours in one row.', 'Ek row me teen COUNT flavours.'],
         ['SELECT COUNT(*) AS students, COUNT(DISTINCT city) AS hometowns, COUNT(email) AS with_email FROM students;', 'SELECT COUNT(*) AS students, COUNT(DISTINCT city) AS hometowns, COUNT(email) AS with_email FROM students;'],
         ['Expected: 50, 10, 41.', 'Expected: 50, 10, 41.']],
        { checkColumnNames: true },
      ),
    ],
  },

  {
    id: 'p2',
    kind: 'mini',
    moduleNumber: 30,
    order: 2,
    title: { en: 'Sales Analytics', hi: 'Sales Analytics' },
    subtitle: { en: 'Six revenue questions on the e-commerce database', hi: 'E-commerce database par chhe revenue sawal' },
    dataset: 'ecommerce',
    intro: {
      en: 'The finance team needs a revenue picture across payment rails, statuses and months. Six requests, each one query: totals, rails, status economics, tier value, the monthly line and the heavy hitters benchmark.',
      hi: 'Finance team ko payment rails, statuses aur mahino ke paar revenue ka picture chahiye. Chhe requests, har ek ek query: totals, rails, status economics, tier value, monthly line aur heavy-hitters benchmark.',
    },
    skillsTested: ['SUM', 'GROUP BY', 'HAVING', 'JOIN', 'ROUND'],
    estimatedTime: '30 min',
    tasks: [
      t('task-1', 'easy',
        ['The board opens with one number.', 'Board ek number se shuru hota hai.'],
        ['Total lifetime revenue across all payments, rounded to 2 decimals, aliased revenue.', 'Saari payments ka total lifetime revenue, 2 decimals par rounded, aliased revenue.'],
        'SELECT ROUND(SUM(amount), 2) AS revenue FROM payments;',
        undefined,
        [['One aggregate on the money table.', 'Money table par ek aggregate.'],
         ['SELECT ROUND(SUM(amount), 2) AS revenue FROM payments;', 'SELECT ROUND(SUM(amount), 2) AS revenue FROM payments;'],
         ['≈ 37.8 million.', '≈ 37.8 million.']],
        { checkColumnNames: true },
      ),
      t('task-2', 'easy',
        ['Payments ops wants rail-level totals.', 'Payments ops rail-level totals chahta hai.'],
        ['Revenue per payment method (rounded), sorted by revenue descending. Columns: payment_method, revenue.', 'Har payment method ki revenue (rounded), revenue se utarte sorted. Columns: payment_method, revenue.'],
        'SELECT payment_method, ROUND(SUM(amount), 2) AS revenue FROM payments GROUP BY payment_method ORDER BY revenue DESC;',
        undefined,
        [['Group by rail, round the sum, sort.', 'Rail se group, sum round, sort.'],
         ['SELECT payment_method, ROUND(SUM(amount), 2) AS revenue FROM payments GROUP BY payment_method ORDER BY revenue DESC;', 'SELECT payment_method, ROUND(SUM(amount), 2) AS revenue FROM payments GROUP BY payment_method ORDER BY revenue DESC;'],
         ['Netbanking leads both usage and revenue.', 'Netbanking usage aur revenue dono me sabse aage.']],
        { ignoreRowOrder: false },
      ),
      t('task-3', 'medium',
        ['Operations tracks the pipeline economically.', 'Operations pipeline ko paise ke hisaab se track karta hai.'],
        ['Per order status: order count and revenue (rounded). Columns: status, orders, revenue. Sorted by orders descending.', 'Har order status ke liye: order count aur revenue (rounded). Columns: status, orders, revenue. Orders se utarte sorted.'],
        'SELECT o.status, COUNT(*) AS orders, ROUND(SUM(p.amount), 2) AS revenue\nFROM orders o JOIN payments p ON p.order_id = o.id\nGROUP BY o.status ORDER BY orders DESC;',
        undefined,
        [['Join orders to payments; group the status.', 'Orders ko payments se join karo; status group karo.'],
         ['SELECT o.status, COUNT(*) AS orders, ROUND(SUM(p.amount), 2) AS revenue FROM orders o JOIN payments p ON p.order_id = o.id GROUP BY o.status ORDER BY orders DESC;', 'SELECT o.status, COUNT(*) AS orders, ROUND(SUM(p.amount), 2) AS revenue FROM orders o JOIN payments p ON p.order_id = o.id GROUP BY o.status ORDER BY orders DESC;'],
         ['Pending and cancelled tie at the top by count.', 'Count me pending aur cancelled upar barabar hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-4', 'medium',
        ['Marketing segments by membership tier.', 'Marketing membership tier se segment karti hai.'],
        ['Per customer tier: customer count and average spend per customer (rounded). Columns: customer_type, customers, avg_spend. Sorted by customer_type.', 'Har customer tier ke liye: customer count aur average spend per customer (rounded). Columns: customer_type, customers, avg_spend. customer_type se sorted.'],
        'SELECT c.customer_type, COUNT(DISTINCT c.id) AS customers, ROUND(SUM(p.amount) / COUNT(DISTINCT c.id), 2) AS avg_spend\nFROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\nGROUP BY c.customer_type ORDER BY c.customer_type;',
        undefined,
        [['One join chain, distinct customers as denominator.', 'Ek join chain, denominator me distinct customers.'],
         ['SELECT c.customer_type, COUNT(DISTINCT c.id) AS customers, ROUND(SUM(p.amount)/COUNT(DISTINCT c.id),2) AS avg_spend FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id GROUP BY c.customer_type ORDER BY c.customer_type;', 'SELECT c.customer_type, COUNT(DISTINCT c.id) AS customers, ROUND(SUM(p.amount)/COUNT(DISTINCT c.id),2) AS avg_spend FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id GROUP BY c.customer_type ORDER BY c.customer_type;'],
         ['VIPs average the highest per head.', 'VIPs per head sabse unchi average rakhte hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-5', 'hard',
        ['The growth review wants the monthly line.', 'Growth review monthly line chahta hai.'],
        ['Revenue per month (substr of order_date), rounded, sorted by month. Columns: month, revenue.', 'Har mahine ki revenue (order_date ka substr), rounded, month se sorted. Columns: month, revenue.'],
        "SELECT substr(o.order_date, 1, 7) AS month, ROUND(SUM(p.amount), 2) AS revenue\nFROM orders o JOIN payments p ON p.order_id = o.id\nGROUP BY substr(o.order_date, 1, 7) ORDER BY month;",
        undefined,
        [['Group by the month expression on ORDER date.', 'ORDER date par month expression se group karo.'],
         ["SELECT substr(o.order_date,1,7) AS month, ROUND(SUM(p.amount),2) AS revenue FROM orders o JOIN payments p ON p.order_id=o.id GROUP BY substr(o.order_date,1,7) ORDER BY month;", "SELECT substr(o.order_date,1,7) AS month, ROUND(SUM(p.amount),2) AS revenue FROM orders o JOIN payments p ON p.order_id=o.id GROUP BY substr(o.order_date,1,7) ORDER BY month;"],
         ['Twelve points on the line.', 'Line par barah points.']],
        { ignoreRowOrder: false },
      ),
      t('task-6', 'very_hard',
        ['Retention asks who carries the business.', 'Retention poochta hai business kaun dhaaran karta hai.'],
        ['Customers whose total spend exceeds the average per-customer spend — name and total (rounded), sorted by total descending.', 'Wo customers jinka total kharch per-customer average se zyada — naam aur total (rounded), total se utarte sorted.'],
        'SELECT c.name, ROUND(SUM(p.amount), 2) AS total\nFROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\nGROUP BY c.id, c.name\nHAVING SUM(p.amount) > (\n  SELECT AVG(s) FROM (\n    SELECT SUM(p2.amount) AS s FROM payments p2 JOIN orders o2 ON o2.id = p2.order_id GROUP BY o2.customer_id\n  )\n)\nORDER BY total DESC;',
        undefined,
        [['Group per customer; gate against the nested average.', 'Per customer group; nested average se gate.'],
         ['HAVING SUM(p.amount) > (SELECT AVG(s) FROM (SELECT SUM(p2.amount) AS s FROM payments p2 JOIN orders o2 ON o2.id = p2.order_id GROUP BY o2.customer_id));', 'HAVING SUM(p.amount) > (SELECT AVG(s) FROM (SELECT SUM(p2.amount) AS s FROM payments p2 JOIN orders o2 ON o2.id = p2.order_id GROUP BY o2.customer_id));'],
         ['About forty customers beat the average.', 'Lagbhag chalis customers average se aage hain.']],
        { ignoreRowOrder: false },
      ),
    ],
  },
];

const PROJECTS_PART2: Project[] = [
  {
    id: 'p4',
    kind: 'mini',
    moduleNumber: 40,
    order: 3,
    title: { en: 'Order Management Queries', hi: 'Order Management Queries' },
    subtitle: { en: 'Five fulfilment-desk requests on live order data', hi: 'Live order data par paanch fulfilment-desk requests' },
    dataset: 'ecommerce',
    intro: {
      en: 'The fulfilment desk lives inside the order pipeline: pending to shipped to delivered or returned. Five requests exercise the full toolkit on that flow — pivots, anti-joins, rankings and conditional aggregates.',
      hi: 'Fulfilment desk order pipeline ke andar jeeti hai: pending se shipped se delivered ya returned. Paanch requests us flow par poora toolkit chalati hain — pivots, anti-joins, rankings aur conditional aggregates.',
    },
    skillsTested: ['CASE', 'LEFT JOIN', 'windows', 'GROUP BY', 'subqueries'],
    estimatedTime: '25 min',
    tasks: [
      t('task-1', 'easy',
        ['The desk wants one dashboard row instead of five queries.', 'Desk paanch queries ki jagah ek dashboard row chahta hai.'],
        ['One row: delivered count, cancelled count and delivered revenue (rounded). Columns: delivered, cancelled, revenue.', 'Ek row: delivered count, cancelled count aur delivered revenue (rounded). Columns: delivered, cancelled, revenue.'],
        "SELECT\n  SUM(CASE WHEN o.status = 'delivered' THEN 1 ELSE 0 END) AS delivered,\n  SUM(CASE WHEN o.status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled,\n  ROUND(SUM(CASE WHEN o.status = 'delivered' THEN p.amount ELSE 0 END), 2) AS revenue\nFROM orders o JOIN payments p ON p.order_id = o.id;",
        undefined,
        [['Three conditional aggregates, one row.', 'Teen conditional aggregates, ek row.'],
         ["SUM(CASE WHEN o.status='delivered' THEN 1 ELSE 0 END) — the counting idiom.", "SUM(CASE WHEN o.status='delivered' THEN 1 ELSE 0 END) — counting idiom."],
         ['98 delivered · 105 cancelled on this data.', 'Is data par 98 delivered · 105 cancelled.']],
        { checkColumnNames: true },
      ),
      t('task-2', 'easy',
        ['Service recovery targets broken promises.', 'Service recovery toote vaade ko target karti hai.'],
        ['Customers who have NOT received a single delivered order — names, via LEFT JOIN with the status filter in ON (NOT EXISTS also passes).', 'Jo customers ko ek bhi delivered order nahi mila — naam, LEFT JOIN se, status filter ON me (NOT EXISTS bhi chalega).'],
        "SELECT c.name\nFROM customers c LEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'delivered'\nWHERE o.id IS NULL;",
        undefined,
        [['The status filter belongs inside the ON clause.', 'Status filter ON clause ke andar rehta hai.'],
         ["SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'delivered' WHERE o.id IS NULL;", "SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'delivered' WHERE o.id IS NULL;"],
         ['34 customers are waiting on their first delivery.', '34 customers apni pehli delivery ka intezaar kar rahe hain.']],
      ),
      t('task-3', 'medium',
        ['The desk ranks products by fulfilment value.', 'Desk products ko fulfilment value se rank karta hai.'],
        ['Top 5 products by total line revenue (SUM of order_items.subtotal), with DENSE_RANK. Columns: name, revenue, drnk. Sorted by drnk, name.', 'Top 5 products total line revenue se (order_items.subtotal ka SUM), DENSE_RANK ke saath. Columns: name, revenue, drnk. drnk, name se sorted.'],
        'WITH product_rev AS (\n  SELECT pr.name, SUM(oi.subtotal) AS revenue\n  FROM order_items oi JOIN products pr ON pr.id = oi.product_id\n  GROUP BY pr.id, pr.name\n)\nSELECT name, ROUND(revenue, 2) AS revenue, DENSE_RANK() OVER (ORDER BY revenue DESC) AS drnk\nFROM product_rev ORDER BY drnk, name LIMIT 5;',
        undefined,
        [['Aggregate first; dense rank the aggregate.', 'Pehle aggregate; phir uska dense rank.'],
         ['WITH product_rev AS (…) SELECT name, ROUND(revenue,2), DENSE_RANK() OVER (ORDER BY revenue DESC) FROM product_rev ORDER BY 3, name LIMIT 5;', 'WITH product_rev AS (…) SELECT name, ROUND(revenue,2), DENSE_RANK() OVER (ORDER BY revenue DESC) FROM product_rev ORDER BY 3, name LIMIT 5;'],
         ['Ties share steps — more than five rows can appear.', 'Ties steps share karti hain — paanch se zyada rows dikh sakti hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-4', 'medium',
        ['Finance reconciles money against fulfilment.', 'Finance paise ko fulfilment se milaati hai.'],
        ['Per status, revenue collected — but only for statuses with at least 1,000,000 total. Columns: status, revenue (rounded). Sorted by revenue descending.', 'Har status ki collected revenue — par sirf 10,00,000 se zyada wale statuses. Columns: status, revenue (rounded). Revenue se utarte sorted.'],
        'SELECT o.status, ROUND(SUM(p.amount), 2) AS revenue\nFROM orders o JOIN payments p ON p.order_id = o.id\nGROUP BY o.status HAVING SUM(p.amount) >= 1000000\nORDER BY revenue DESC;',
        undefined,
        [['GROUP BY then HAVING on the aggregate.', 'Pehle GROUP BY phir aggregate par HAVING.'],
         ['SELECT o.status, ROUND(SUM(p.amount),2) AS revenue FROM orders o JOIN payments p ON p.order_id = o.id GROUP BY o.status HAVING SUM(p.amount) >= 1000000 ORDER BY revenue DESC;', 'SELECT o.status, ROUND(SUM(p.amount),2) AS revenue FROM orders o JOIN payments p ON p.order_id = o.id GROUP BY o.status HAVING SUM(p.amount) >= 1000000 ORDER BY revenue DESC;'],
         ['All five statuses clear a million in this data.', 'Is data me paanchon statuses million paar karte hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-5', 'hard',
        ['The city page shows regional operations.', 'City page regional operations dikhata hai.'],
        ['Per city: total customers and delivered-order customers (distinct), keeping cities where nobody delivered — LEFT JOIN with the status filter in ON. Columns: city, customers, delivered_buyers. Sorted by city.', 'Har city: kul customers aur delivered-order customers (distinct), wo cities bhi jahan kisi ko delivery nahi mili — LEFT JOIN status filter ON me. Columns: city, customers, delivered_buyers. City se sorted.'],
        "SELECT c.city,\n  COUNT(DISTINCT c.id) AS customers,\n  COUNT(DISTINCT CASE WHEN o.status = 'delivered' THEN o.customer_id END) AS delivered_buyers\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.city ORDER BY c.city;",
        undefined,
        [['LEFT JOIN keeps every city; CASE inside COUNT filters delivered.', 'LEFT JOIN har city bachata hai; COUNT ke andar CASE delivered filter karta hai.'],
         ["COUNT(DISTINCT CASE WHEN o.status='delivered' THEN o.customer_id END) — NULL-else does the filtering.", "COUNT(DISTINCT CASE WHEN o.status='delivered' THEN o.customer_id END) — NULL-else hi filter karta hai."],
         ['Some cities show delivered_buyers < customers.', 'Kuch cities me delivered_buyers < customers dikhta hai.']],
        { ignoreRowOrder: false },
      ),
    ],
  },
];

const PROJECTS_PART3: Project[] = [
  {
    id: 'p5',
    kind: 'mini',
    moduleNumber: 50,
    order: 4,
    title: { en: 'Review System Analytics', hi: 'Review System Analytics' },
    subtitle: { en: 'Five product-reputation questions on the full database', hi: 'Poore database par paanch product-reputation sawal' },
    dataset: 'advanced',
    intro: {
      en: 'The product team mines the review system: rating distribution, per-product averages, polarising products, silent products, and a reusable view for the weekly report.',
      hi: 'Product team review system kholdi hai: rating distribution, per-product averages, polarising products, chup products, aur weekly report ke liye reusable view.',
    },
    skillsTested: ['AVG', 'windows', 'CTE', 'views', 'NOT EXISTS'],
    estimatedTime: '30 min',
    tasks: [
      t('task-1', 'easy',
        ['Sentiment overview for the weekly quality meeting.', 'Weekly quality meeting ke liye sentiment overview.'],
        ['Rating distribution: rating and count (aliased n), plus each rating\'s share of all reviews (rounded 1 decimal, aliased pct). Sorted by rating.', 'Rating distribution: rating aur count (aliased n), plus har rating ka saari reviews me hissa (1 decimal par, aliased pct). Rating se sorted.'],
        'SELECT rating, COUNT(*) AS n,\n  ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM reviews), 1) AS pct\nFROM reviews GROUP BY rating ORDER BY rating;',
        undefined,
        [['The denominator is a scalar subquery over the whole table.', 'Denominator poori table par scalar subquery hai.'],
         ['SELECT rating, COUNT(*) AS n, ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM reviews), 1) AS pct FROM reviews GROUP BY rating ORDER BY rating;', 'SELECT rating, COUNT(*) AS n, ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM reviews), 1) AS pct FROM reviews GROUP BY rating ORDER BY rating;'],
         ['5-star reviews dominate.', '5-star reviews haavi hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-2', 'medium',
        ['The catalogue page shows quality tiers.', 'Catalogue page quality tiers dikhata hai.'],
        ['Products with at least 2 reviews: product_id, avg_rating (rounded 2) and DENSE_RANK by average descending. Columns: product_id, avg_rating, drnk. Sorted by drnk, product_id. LIMIT 10.', 'Kam se kam 2 reviews wale products: product_id, avg_rating (rounded 2) aur average se utarta DENSE_RANK. Columns: product_id, avg_rating, drnk. drnk, product_id se sorted. LIMIT 10.'],
        'WITH product_avg AS (\n  SELECT product_id, ROUND(AVG(rating), 2) AS avg_rating\n  FROM reviews GROUP BY product_id HAVING COUNT(*) >= 2\n)\nSELECT product_id, avg_rating, DENSE_RANK() OVER (ORDER BY avg_rating DESC) AS drnk\nFROM product_avg ORDER BY drnk, product_id LIMIT 10;',
        undefined,
        [['Averages with the review-count gate, then dense rank.', 'Review-count gate ke saath averages, phir dense rank.'],
         ['WITH product_avg AS (SELECT product_id, ROUND(AVG(rating),2) AS avg_rating FROM reviews GROUP BY product_id HAVING COUNT(*) >= 2) SELECT … DENSE_RANK() OVER (ORDER BY avg_rating DESC) … LIMIT 10;', 'WITH product_avg AS (SELECT product_id, ROUND(AVG(rating),2) AS avg_rating FROM reviews GROUP BY product_id HAVING COUNT(*) >= 2) SELECT … DENSE_RANK() OVER (ORDER BY avg_rating DESC) … LIMIT 10;'],
         ['Tied averages share steps.', 'Tied averages steps share karti hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-3', 'medium',
        ['The merchandising lead hunts polarising products.', 'Merchandising lead polarising products ka shikar karta hai.'],
        ['Products with 3+ reviews whose ratings SPREAD widely (spread = MAX − MIN = 4). Columns: product_id, avg_rating, spread. Sorted by product_id.', '3+ reviews wale products jinki ratings ka SPREAD wide hai (spread = MAX − MIN = 4). Columns: product_id, avg_rating, spread. product_id se sorted.'],
        'SELECT product_id, ROUND(AVG(rating), 2) AS avg_rating, MAX(rating) - MIN(rating) AS spread\nFROM reviews\nGROUP BY product_id HAVING COUNT(*) >= 3 AND MAX(rating) - MIN(rating) = 4\nORDER BY product_id;',
        undefined,
        [['MAX − MIN measures disagreement; the HAVING gates it.', 'MAX − MIN matbhed naapta hai; HAVING use gate karta hai.'],
         ['SELECT product_id, ROUND(AVG(rating),2) AS avg_rating, MAX(rating) - MIN(rating) AS spread FROM reviews GROUP BY product_id HAVING COUNT(*) >= 3 AND MAX(rating) - MIN(rating) = 4 ORDER BY product_id;', 'SELECT product_id, ROUND(AVG(rating),2) AS avg_rating, MAX(rating) - MIN(rating) AS spread FROM reviews GROUP BY product_id HAVING COUNT(*) >= 3 AND MAX(rating) - MIN(rating) = 4 ORDER BY product_id;'],
         ['A handful of products split the room.', 'Chand products kamra baant dete hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-4', 'medium',
        ['The category pages need silent-product flags.', 'Category pages ko chup-product flags chahiye.'],
        ['Active products (is_active = 1) with NO review at all — product ids via NOT EXISTS. Sorted by id.', 'Active products (is_active = 1) jinpar KOI review nahi — product ids NOT EXISTS se. Id se sorted.'],
        'SELECT p.id\nFROM products p\nWHERE p.is_active = 1 AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.product_id = p.id)\nORDER BY p.id;',
        undefined,
        [['The anti-join on reviews; the active flag outside.', 'Reviews par anti-join; active flag bahar.'],
         ['SELECT p.id FROM products p WHERE p.is_active = 1 AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.product_id = p.id) ORDER BY p.id;', 'SELECT p.id FROM products p WHERE p.is_active = 1 AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.product_id = p.id) ORDER BY p.id;'],
         ['Roughly a third of active products are unreviewed.', 'Lagbhag tees active products unreviewed hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-5', 'hard',
        ['The weekly report needs a reusable asset.', 'Weekly report ko reusable asset chahiye.'],
        ['CREATE VIEW v_product_quality (product_id, name, review_count, avg_rating over products LEFT JOIN reviews), then SELECT from it ordered by avg_rating DESC, review_count DESC LIMIT 8 — columns: product_id, name, review_count, avg_rating.', 'CREATE VIEW v_product_quality (products LEFT JOIN reviews par product_id, name, review_count, avg_rating), phir usse padho avg_rating DESC, review_count DESC LIMIT 8 — columns: product_id, name, review_count, avg_rating.'],
        'DROP VIEW IF EXISTS v_product_quality;\nCREATE VIEW v_product_quality AS\nSELECT pr.id AS product_id, pr.name, COUNT(r.id) AS review_count, ROUND(AVG(r.rating), 2) AS avg_rating\nFROM products pr LEFT JOIN reviews r ON r.product_id = pr.id\nGROUP BY pr.id, pr.name;\nSELECT product_id, name, review_count, avg_rating FROM v_product_quality ORDER BY avg_rating DESC, review_count DESC LIMIT 8;',
        'SELECT product_id, name, review_count, avg_rating FROM v_product_quality ORDER BY avg_rating DESC, review_count DESC LIMIT 8',
        [['The LEFT JOIN keeps unreviewed products with NULL averages.', 'LEFT JOIN unreviewed products ko NULL averages ke saath bachata hai.'],
         ['DROP VIEW IF EXISTS first, then CREATE, then SELECT.', 'Pehle DROP VIEW IF EXISTS, phir CREATE, phir SELECT.'],
         ['NULLs sort last in DESC — reviewed products lead.', 'DESC me NULL aakhir me — reviewed products aage.']],
        { ignoreRowOrder: false },
      ),
    ],
  },
];

const PROJECTS_PART4: Project[] = [
  {
    id: 'p3',
    kind: 'mini',
    moduleNumber: 49,
    order: 5,
    title: { en: 'Advanced Analytics', hi: 'Advanced Analytics' },
    subtitle: { en: 'Six expert questions: windows + CTEs on the full database', hi: 'Poore database par chhe expert sawal: windows + CTEs' },
    dataset: 'advanced',
    intro: {
      en: 'The analytics team\'s expert sprint: rankings, month-over-month growth, cumulative inventory movement, churn cohorts and segment economics. Every answer is a CTE pipeline with a window on top.',
      hi: 'Analytics team ka expert sprint: rankings, month-over-month growth, cumulative inventory movement, churn cohorts aur segment economics. Har jawab ek CTE pipeline hai jiska upar window.',
    },
    skillsTested: ['RANK', 'LAG', 'running totals', 'CTE', 'PARTITION BY'],
    estimatedTime: '40 min',
    tasks: [
      t('task-1', 'easy',
        ['Operations wants the shipping league at a glance.', 'Operations shipping league ek nazar me chahta hai.'],
        ['Shipping statuses with counts and RANK by volume. Columns: shipping_status, n, rnk. Sorted by rnk, shipping_status.', 'Shipping statuses counts aur RANK volume se. Columns: shipping_status, n, rnk. rnk, shipping_status se sorted.'],
        'SELECT shipping_status, COUNT(*) AS n,\n  RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk\nFROM shipping GROUP BY shipping_status ORDER BY rnk, shipping_status;',
        undefined,
        [['Group statuses, then rank the counts.', 'Statuses group karo, phir counts rank karo.'],
         ['SELECT shipping_status, COUNT(*) AS n, RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk FROM shipping GROUP BY shipping_status ORDER BY rnk, shipping_status;', 'SELECT shipping_status, COUNT(*) AS n, RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk FROM shipping GROUP BY shipping_status ORDER BY rnk, shipping_status;'],
         ['delivered (250) leads by far.', 'delivered (250) bahut aage hai.']],
        { ignoreRowOrder: false },
      ),
      t('task-2', 'easy',
        ['The pulse check: cumulative inventory movement.', 'Pulse check: cumulative inventory movement.'],
        ['The 12 latest inventory entries (id descending) with running totals of change_quantity (computed ascending by id). Columns: id, change_quantity, running_total. Sorted by id descending. LIMIT 12.', '12 sabse naye inventory entries (id se utarte) change_quantity ke running totals ke saath (id se chadhte compute). Columns: id, change_quantity, running_total. Id se utarte sorted. LIMIT 12.'],
        'SELECT id, change_quantity, running_total FROM (\n  SELECT id, change_quantity,\n    SUM(change_quantity) OVER (ORDER BY id) AS running_total\n  FROM inventory_log\n) ORDER BY id DESC LIMIT 12;',
        undefined,
        [['Window ORDER BY id defines accumulation; the outer ORDER flips display.', 'Window ka ORDER BY id accumulation define karta hai; bahar ka ORDER display ulta karta hai.'],
         ['SELECT id, change_quantity, running_total FROM (SELECT id, change_quantity, SUM(change_quantity) OVER (ORDER BY id) AS running_total FROM inventory_log) ORDER BY id DESC LIMIT 12;', 'SELECT id, change_quantity, running_total FROM (SELECT id, change_quantity, SUM(change_quantity) OVER (ORDER BY id) AS running_total FROM inventory_log) ORDER BY id DESC LIMIT 12;'],
         ['The top row is the final net position.', 'Sabse upar wali row final net position hai.']],
        { ignoreRowOrder: false },
      ),
      t('task-3', 'medium',
        ['The review team ranks reliable products.', 'Review team reliable products rank karti hai.'],
        ['Products with 2+ reviews ranked by average rating with DENSE_RANK — product_id, avg_rating (rounded 2), drnk. Sorted by drnk, product_id. LIMIT 8.', '2+ reviews wale products average rating se DENSE_RANK ke saath — product_id, avg_rating (rounded 2), drnk. drnk, product_id se sorted. LIMIT 8.'],
        'WITH product_avg AS (\n  SELECT product_id, ROUND(AVG(rating), 2) AS avg_rating\n  FROM reviews GROUP BY product_id HAVING COUNT(*) >= 2\n)\nSELECT product_id, avg_rating, DENSE_RANK() OVER (ORDER BY avg_rating DESC) AS drnk\nFROM product_avg ORDER BY drnk, product_id LIMIT 8;',
        undefined,
        [['Averages first (with the gate), dense rank second.', 'Pehle averages (gate ke saath), doosra dense rank.'],
         ['WITH product_avg AS (…) SELECT product_id, avg_rating, DENSE_RANK() OVER (ORDER BY avg_rating DESC) AS drnk FROM product_avg ORDER BY drnk, product_id LIMIT 8;', 'WITH product_avg AS (…) SELECT product_id, avg_rating, DENSE_RANK() OVER (ORDER BY avg_rating DESC) AS drnk FROM product_avg ORDER BY drnk, product_id LIMIT 8;'],
         ['Perfect averages share the top step.', 'Perfect averages top step share karte hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-4', 'medium',
        ['Churn analysis: who went quiet?', 'Churn analysis: kaun chup ho gaya?'],
        ['Customers whose LAST order is older than 2023-07-01 — name and last_order. Columns: name, last_order. Sorted by last_order, name. LIMIT 10.', 'Jinka AAKHRI order 2023-07-01 se purana — naam aur last_order. Columns: name, last_order. last_order, name se sorted. LIMIT 10.'],
        'WITH last_order AS (\n  SELECT c.name, MAX(o.order_date) AS last_order\n  FROM customers c JOIN orders o ON o.customer_id = c.id\n  GROUP BY c.id, c.name\n)\nSELECT name, last_order FROM last_order\nWHERE last_order < \'2023-07-01\'\nORDER BY last_order, name LIMIT 10;',
        undefined,
        [['MAX(order_date) per customer, then the date threshold.', 'Per customer MAX(order_date), phir date threshold.'],
         ["WITH last_order AS (SELECT c.name, MAX(o.order_date) AS last_order FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.id, c.name) SELECT name, last_order FROM last_order WHERE last_order < '2023-07-01' ORDER BY last_order, name LIMIT 10;", "WITH last_order AS (SELECT c.name, MAX(o.order_date) AS last_order FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.id, c.name) SELECT name, last_order FROM last_order WHERE last_order < '2023-07-01' ORDER BY last_order, name LIMIT 10;"],
         ['The watchlist of at-risk customers.', 'At-risk customers ki watchlist.']],
        { ignoreRowOrder: false },
      ),
      t('task-5', 'hard',
        ['The growth line: delivered revenue month by month.', 'Growth line: mahine-dar-mahine delivered revenue.'],
        ['CTE monthly (delivered revenue per month), CTE growth (LAG prev), final: month, revenue (rounded), growth_pct (1 decimal) — months with a previous only. Columns: month, revenue, growth_pct. Sorted by month. LIMIT 8.', 'CTE monthly (monthly delivered revenue), CTE growth (LAG prev), final: month, revenue (rounded), growth_pct (1 decimal) — sirf pichla mahina walon ke liye. Columns: month, revenue, growth_pct. Month se sorted. LIMIT 8.'],
        "WITH monthly AS (\n  SELECT substr(o.order_date, 1, 7) AS month, SUM(p.amount) AS revenue\n  FROM orders o JOIN payments p ON p.order_id = o.id\n  WHERE o.status = 'delivered'\n  GROUP BY substr(o.order_date, 1, 7)\n),\ngrowth AS (\n  SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev FROM monthly\n)\nSELECT month, ROUND(revenue, 2) AS revenue,\n  ROUND(100.0 * (revenue - prev) / prev, 1) AS growth_pct\nFROM growth WHERE prev IS NOT NULL ORDER BY month LIMIT 8;",
        undefined,
        [['Three levels: sums → lag → filter+formula.', 'Teen level: sums → lag → filter+formula.'],
         ['The delivered filter lives in the FIRST step (WHERE on raw rows).', 'Delivered filter PEHLE step me rehta hai (raw rows par WHERE).'],
         ['Eleven rows (Feb–Dec) — January is filtered by design.', 'Gyarah rows (Feb–Dec) — January design se filtered hai.']],
        { ignoreRowOrder: false },
      ),
      t('task-6', 'very_hard',
        ['Segment economics for the retention board.', 'Retention board ke liye segment economics.'],
        ['Per segment: customer count and average customer spend (through segments→customers→orders→payments, LEFT JOINs). Columns: segment_name, customers, avg_spend (rounded 2). Sorted by customers descending.', 'Har segment: customer count aur average customer kharch (segments→customers→orders→payments se, LEFT JOINs). Columns: segment_name, customers, avg_spend (rounded 2). Customers se utarte sorted.'],
        'WITH seg_spend AS (\n  SELECT cs.segment_name, c.id, SUM(p.amount) AS total\n  FROM customer_segments cs\n  JOIN customers c ON c.id = cs.customer_id\n  LEFT JOIN orders o ON o.customer_id = c.id\n  LEFT JOIN payments p ON p.order_id = o.id\n  GROUP BY cs.segment_name, c.id\n)\nSELECT segment_name, COUNT(*) AS customers, ROUND(AVG(total), 2) AS avg_spend\nFROM seg_spend GROUP BY segment_name ORDER BY customers DESC;',
        undefined,
        [['LEFT JOINs keep zero-order customers (their spend is NULL — AVG skips).', 'LEFT JOINs zero-order customers bachate hain (kharch NULL — AVG skip).'],
         ['Step 1: spend per (segment, customer). Step 2: average per segment.', 'Step 1: har (segment, customer) ka kharch. Step 2: har segment ka average.'],
         ['regular and vip lead by count.', 'Count me regular aur vip aage hain.']],
        { ignoreRowOrder: false },
      ),
    ],
  },
  {
    id: 'p6',
    kind: 'mini',
    moduleNumber: 59,
    order: 6,
    title: { en: 'Performance Optimization', hi: 'Performance Optimization' },
    subtitle: { en: 'Four before/after optimisation loops, proven with plans', hi: 'Chaar before/after optimisation loops, plans se saabit' },
    dataset: 'advanced',
    intro: {
      en: 'The performance desk: four complaints, four full loops. EXPLAIN the bad shape, apply the lever (sargable rewrite, targeted index, composite), EXPLAIN the improvement. Every submission is a deployable before/after pair.',
      hi: 'Performance desk: chaar shikayatein, chaar poore loop. Bura shape EXPLAIN karo, lever lagao (sargable rewrite, targeted index, composite), sudhaar EXPLAIN karo. Har submission deployable before/after jodi hai.',
    },
    skillsTested: ['EXPLAIN QUERY PLAN', 'CREATE INDEX', 'sargable', 'composite index'],
    estimatedTime: '45 min',
    tasks: [
      t('task-1', 'easy',
        ['Complaint: "the June report scans everything."', 'Shikayat: "June report sab kuch scan karti hai."'],
        ['EXPLAIN the bad shape (substr on order_date), then EXPLAIN the sargable June range. Submit both EXPLAIN statements.', 'Bura shape EXPLAIN karo (order_date par substr), phir sargable June range EXPLAIN karo. Dono EXPLAIN submit karo.'],
        "EXPLAIN QUERY PLAN SELECT * FROM orders WHERE substr(order_date, 1, 7) = '2023-06';\nEXPLAIN QUERY PLAN SELECT * FROM orders WHERE order_date >= '2023-06-01' AND order_date < '2023-07-01';",
        undefined,
        [['Bad plan first, good plan second — the diagnostic pair.', 'Pehla bura plan, doosra achha plan — diagnostic jodi.'],
         ['The rewrite turns a function-wrapped filter into a half-open range.', 'Rewrite function-wrapped filter ko half-open range me badalta hai.'],
         ['Read both outputs — that is the practice.', 'Dono output padho — wahi practice hai.']],
      ),
      t('task-2', 'easy',
        ['Complaint: "the status lookup walks the whole table."', 'Shikayat: "status lookup poori table chalti hai."'],
        ['CREATE INDEX idx_p_orders_status ON orders(status), then EXPLAIN SELECT * FROM orders WHERE status = \'pending\'. Submit both.', 'CREATE INDEX idx_p_orders_status ON orders(status), phir EXPLAIN SELECT * FROM orders WHERE status = \'pending\'. Dono submit karo.'],
        "CREATE INDEX idx_p_orders_status ON orders(status);\nEXPLAIN QUERY PLAN SELECT * FROM orders WHERE status = 'pending';",
        "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_p_orders_status'",
        [['One index, one re-plan.', 'Ek index, ek re-plan.'],
         ['CREATE INDEX idx_p_orders_status ON orders(status);', 'CREATE INDEX idx_p_orders_status ON orders(status);'],
         ['The plan flips from SCAN to SEARCH.', 'Plan SCAN se SEARCH ho jaata hai.']],
      ),
      t('task-3', 'medium',
        ['Complaint: "the rail grouping sorts in memory every run."', 'Shikayat: "rail grouping har run me memory me sort karti hai."'],
        ['EXPLAIN the GROUP BY payment_method; CREATE INDEX idx_p_pay_method ON payments(payment_method); EXPLAIN again. Submit all three.', 'GROUP BY payment_method EXPLAIN karo; CREATE INDEX idx_p_pay_method ON payments(payment_method); dobara EXPLAIN. Teeno submit karo.'],
        "EXPLAIN QUERY PLAN SELECT payment_method, COUNT(*) FROM payments GROUP BY payment_method;\nCREATE INDEX idx_p_pay_method ON payments(payment_method);\nEXPLAIN QUERY PLAN SELECT payment_method, COUNT(*) FROM payments GROUP BY payment_method;",
        "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_p_pay_method'",
        [['Grouping over index order can drop the temp tree.', 'Index order par grouping temp tree gira sakti hai.'],
         ['EXPLAIN → CREATE INDEX → EXPLAIN, one submission.', 'EXPLAIN → CREATE INDEX → EXPLAIN, ek submission.'],
         ['Compare the two plans line by line.', 'Dono plans line-by-line compare karo.']],
      ),
      t('task-4', 'hard',
        ['Complaint: "the order drill-down joins read too much."', 'Shikayat: "order drill-down ke joins bahut padhte hain."'],
        ['EXPLAIN the join (products ⨝ order_items WHERE oi.order_id = 42); CREATE INDEX idx_p_oi_order ON order_items(order_id); EXPLAIN again. Submit all three.', 'Join EXPLAIN karo (products ⨝ order_items WHERE oi.order_id = 42); CREATE INDEX idx_p_oi_order ON order_items(order_id); dobara EXPLAIN. Teeno submit karo.'],
        "EXPLAIN QUERY PLAN SELECT pr.name FROM products pr JOIN order_items oi ON oi.product_id = pr.id WHERE oi.order_id = 42;\nCREATE INDEX idx_p_oi_order ON order_items(order_id);\nEXPLAIN QUERY PLAN SELECT pr.name FROM products pr JOIN order_items oi ON oi.product_id = pr.id WHERE oi.order_id = 42;",
        "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_p_oi_order'",
        [['Index the join/filter column on the big table.', 'Badi table par join/filter column index karo.'],
         ['The composite detail line shows the index columns used.', 'Composite detail line index ke kaunse columns use hue dikhati hai.'],
         ['Before/after pair is the deliverable.', 'Before/after jodi hi deliverable hai.']],
      ),
    ],
  },
];

const PROJECTS_PART5: Project[] = [
  {
    id: 'lp1',
    kind: 'level',
    moduleNumber: 20,
    order: 7,
    title: { en: 'School Report Generator', hi: 'School Report Generator' },
    subtitle: { en: 'The Beginner graduation project — eight office requests', hi: 'Beginner graduation project — aath office requests' },
    dataset: 'school',
    intro: {
      en: 'The annual school report: eight requests from eight desks, covering everything from Beginner — projection, aliases, DISTINCT, every filter operator, NULL handling, multi-level sorts, Top-N and pagination.',
      hi: 'Annual school report: aath desks se aath requests, Beginner ka sab kuch cover karte hue — projection, aliases, DISTINCT, saare filter operators, NULL handling, multi-level sorts, Top-N aur pagination.',
    },
    skillsTested: ['SELECT', 'WHERE', 'IS NULL', 'IN', 'LIKE', 'ORDER BY', 'LIMIT/OFFSET'],
    estimatedTime: '45 min',
    tasks: [
      t('task-1', 'easy',
        ['Cover page: the five most experienced teachers.', 'Cover page: paanch sabse experienced teachers.'],
        ['Name and experience_years, most experienced first, ties by name. LIMIT 5. Sorted by experience descending then name.', 'Name aur experience_years, sabse experienced pehle, ties naam se. LIMIT 5. Experience se utarte phir naam se sorted.'],
        'SELECT name, experience_years FROM teachers ORDER BY experience_years DESC, name LIMIT 5;',
        undefined,
        [['Two-level descending sort plus a cap.', 'Do-level utarta sort aur ek cap.'],
         ['SELECT name, experience_years FROM teachers ORDER BY experience_years DESC, name LIMIT 5;', 'SELECT name, experience_years FROM teachers ORDER BY experience_years DESC, name LIMIT 5;'],
         ['Vikas Nair (20 years) leads.', 'Vikas Nair (20 saal) sabse aage.']],
        { ignoreRowOrder: false },
      ),
      t('task-2', 'easy',
        ['Contact audit: incomplete records.', 'Contact audit: adhoore records.'],
        ['Students with a missing email, sorted by name. Names only.', 'Email missing wale students, naam se sorted. Sirf naam.'],
        'SELECT name FROM students WHERE email IS NULL ORDER BY name;',
        undefined,
        [['The only correct NULL test plus a sort.', 'Sahi NULL test aur ek sort.'],
         ['SELECT name FROM students WHERE email IS NULL ORDER BY name;', 'SELECT name FROM students WHERE email IS NULL ORDER BY name;'],
         ['Nine rows, alphabetical.', 'Nau rows, alphabetical.']],
        { ignoreRowOrder: false },
      ),
      t('task-3', 'medium',
        ['Merit list: high scores across the school.', 'Merit list: school bhar ke unche scores.'],
        ['Graded enrollments with score 90 or above — student_id, course_id, score. Sorted by score descending, id ascending.', 'Graded enrollments jinke score 90 ya upar — student_id, course_id, score. Score se utarte, id se chadhte sorted.'],
        'SELECT student_id, course_id, score FROM enrollments WHERE score IS NOT NULL AND score >= 90 ORDER BY score DESC, id ASC;',
        undefined,
        [['Threshold filter, NULL guard, two-level sort.', 'Threshold filter, NULL guard, do-level sort.'],
         ['SELECT student_id, course_id, score FROM enrollments WHERE score IS NOT NULL AND score >= 90 ORDER BY score DESC, id ASC;', 'SELECT student_id, course_id, score FROM enrollments WHERE score IS NOT NULL AND score >= 90 ORDER BY score DESC, id ASC;'],
         ['Perfect 100s lead the list.', 'Perfect 100s list me sabse aage.']],
        { ignoreRowOrder: false },
      ),
      t('task-4', 'medium',
        ['Regional roll: the metro cohort.', 'Regional roll: metro cohort.'],
        ['Students from Delhi, Mumbai or Bangalore, grouped by city (A→Z) and name within. Columns: name, city.', 'Delhi, Mumbai ya Bangalore ke students, city (A→Z) se grouped, andar naam se. Columns: name, city.'],
        "SELECT name, city FROM students WHERE city IN ('Delhi', 'Mumbai', 'Bangalore') ORDER BY city, name;",
        undefined,
        [['IN for the city set; two-level ascending sort.', 'City set ke liye IN; do-level chadhta sort.'],
         ["SELECT name, city FROM students WHERE city IN ('Delhi','Mumbai','Bangalore') ORDER BY city, name;", "SELECT name, city FROM students WHERE city IN ('Delhi','Mumbai','Bangalore') ORDER BY city, name;"],
         ['Bangalore block first (alphabetically).', 'Bangalore block pehle (alphabetically).']],
        { ignoreRowOrder: false },
      ),
      t('task-5', 'medium',
        ['The honour cities for the district citation.', 'District citation ke liye honour cities.'],
        ['Unique cities that have at least one grade-A student, alphabetical. Column: city.', 'Wo unique cities jahan kam se kam ek grade-A student hai, alphabetical. Column: city.'],
        "SELECT DISTINCT city FROM students WHERE grade = 'A' ORDER BY city;",
        undefined,
        [['DISTINCT + WHERE + ORDER BY stack in this order.', 'DISTINCT + WHERE + ORDER BY isi order me lagte hain.'],
         ["SELECT DISTINCT city FROM students WHERE grade = 'A' ORDER BY city;", "SELECT DISTINCT city FROM students WHERE grade = 'A' ORDER BY city;"],
         ['Filtering happens before deduplication.', 'Filtering dedup se pehle hoti hai.']],
        { ignoreRowOrder: false },
      ),
      t('task-6', 'medium',
        ['Page 3 of the printed honour roll.', 'Printed honour roll ka page 3.'],
        ['Grade-A students sorted by name; rows 11 through 15 (skip 10, take 5). Columns: name, grade.', 'Grade-A students naam se sorted; rows 11 se 15 (10 skip, 5 lo). Columns: name, grade.'],
        "SELECT name, grade FROM students WHERE grade = 'A' ORDER BY name LIMIT 5 OFFSET 10;",
        undefined,
        [['Sorted slice: LIMIT 5 OFFSET 10.', 'Sorted slice: LIMIT 5 OFFSET 10.'],
         ["SELECT name, grade FROM students WHERE grade = 'A' ORDER BY name LIMIT 5 OFFSET 10;", "SELECT name, grade FROM students WHERE grade = 'A' ORDER BY name LIMIT 5 OFFSET 10;"],
         ['Twelve grade-A students exist — this page shows the last two.', 'Barah grade-A students hain — ye page aakhri do dikhata hai.']],
        { ignoreRowOrder: false },
      ),
      t('task-7', 'hard',
        ['The watch list: students needing support.', 'Watch list: support chahiye wale students.'],
        ['Adults (18+) from non-metro cities (not Delhi/Mumbai/Bangalore/Hyderabad) with grades C, D or F. Columns: name, city, grade, age. Sorted by grade then name.', 'Bade (18+) non-metro cities (Delhi/Mumbai/Bangalore/Hyderabad ke alawa) ke grade C, D ya F wale students. Columns: name, city, grade, age. Grade phir naam se sorted.'],
        "SELECT name, city, grade, age FROM students\nWHERE age >= 18 AND city NOT IN ('Delhi','Mumbai','Bangalore','Hyderabad') AND grade IN ('C','D','F')\nORDER BY grade, name;",
        undefined,
        [['Three conditions: age, city exclusion set, grade set.', 'Teen conditions: age, city exclusion set, grade set.'],
         ["SELECT name, city, grade, age FROM students WHERE age >= 18 AND city NOT IN ('Delhi','Mumbai','Bangalore','Hyderabad') AND grade IN ('C','D','F') ORDER BY grade, name;", "SELECT name, city, grade, age FROM students WHERE age >= 18 AND city NOT IN ('Delhi','Mumbai','Bangalore','Hyderabad') AND grade IN ('C','D','F') ORDER BY grade, name;"],
         ['C-grades first, then D, then F.', 'Pehle C, phir D, phir F.']],
        { ignoreRowOrder: false },
      ),
      t('task-8', 'hard',
        ['The compact card for the report cover.', 'Report cover ke liye compact card.'],
        ['One row with three numbers: total students (total), unique hometowns (hometowns), students with emails (with_email). Headers checked.', 'Ek row me teen numbers: kul students (total), unique hometowns (hometowns), email wale students (with_email). Headers check honge.'],
        'SELECT COUNT(*) AS total, COUNT(DISTINCT city) AS hometowns, COUNT(email) AS with_email FROM students;',
        undefined,
        [['COUNT(*) vs COUNT(DISTINCT) vs COUNT(col) — three flavours in one row.', 'COUNT(*) vs COUNT(DISTINCT) vs COUNT(col) — ek row me teen flavours.'],
         ['SELECT COUNT(*) AS total, COUNT(DISTINCT city) AS hometowns, COUNT(email) AS with_email FROM students;', 'SELECT COUNT(*) AS total, COUNT(DISTINCT city) AS hometowns, COUNT(email) AS with_email FROM students;'],
         ['Expected: 50, 10, 41.', 'Expected: 50, 10, 41.']],
        { checkColumnNames: true },
      ),
    ],
  },
];

const PROJECTS_PART6: Project[] = [
  {
    id: 'lp2',
    kind: 'level',
    moduleNumber: 40,
    order: 8,
    title: { en: 'E-Commerce Analytics', hi: 'E-Commerce Analytics' },
    subtitle: { en: 'The Intermediate graduation project — ten business questions', hi: 'Intermediate graduation project — das business sawal' },
    dataset: 'ecommerce',
    intro: {
      en: 'The quarterly business review pack: ten requests spanning the whole Intermediate toolkit — the revenue chain, rail economics, tier behaviour, product leagues, monthly pivots, benchmark subqueries, category trees and the one-number KPI.',
      hi: 'Quarterly business review pack: das requests jo poora Intermediate toolkit cover karti hain — revenue chain, rail economics, tier behaviour, product leagues, monthly pivots, benchmark subqueries, category trees aur ek-number KPI.',
    },
    skillsTested: ['JOIN', 'GROUP BY', 'HAVING', 'subquery', 'CASE', 'windows'],
    estimatedTime: '60 min',
    tasks: [
      t('task-1', 'easy',
        ['The board opens with one number.', 'Board ek number se shuru hota hai.'],
        ['Total lifetime revenue, rounded, aliased revenue.', 'Total lifetime revenue, rounded, aliased revenue.'],
        'SELECT ROUND(SUM(amount), 2) AS revenue FROM payments;',
        undefined,
        [['One aggregate on the money table.', 'Money table par ek aggregate.'],
         ['SELECT ROUND(SUM(amount), 2) AS revenue FROM payments;', 'SELECT ROUND(SUM(amount), 2) AS revenue FROM payments;'],
         ['≈ 37.8 million.', '≈ 37.8 million.']],
        { checkColumnNames: true },
      ),
      t('task-2', 'easy',
        ['Payments ops: rail-level economics.', 'Payments ops: rail-level economics.'],
        ['Per payment method: payments (count) and revenue (rounded). Columns: payment_method, payments, revenue. Sorted by revenue descending.', 'Har payment method: payments (count) aur revenue (rounded). Columns: payment_method, payments, revenue. Revenue se utarte sorted.'],
        'SELECT payment_method, COUNT(*) AS payments, ROUND(SUM(amount), 2) AS revenue\nFROM payments GROUP BY payment_method ORDER BY revenue DESC;',
        undefined,
        [['Group by rail; two aggregates; sort.', 'Rail se group; do aggregates; sort.'],
         ['SELECT payment_method, COUNT(*) AS payments, ROUND(SUM(amount), 2) AS revenue FROM payments GROUP BY payment_method ORDER BY revenue DESC;', 'SELECT payment_method, COUNT(*) AS payments, ROUND(SUM(amount), 2) AS revenue FROM payments GROUP BY payment_method ORDER BY revenue DESC;'],
         ['Netbanking leads on both axes.', 'Netbanking dono axis par aage.']],
        { ignoreRowOrder: false },
      ),
      t('task-3', 'medium',
        ['Pipeline economics for operations.', 'Operations ke liye pipeline economics.'],
        ['Per order status: order count and revenue (rounded). Columns: status, orders, revenue. Sorted by orders descending.', 'Har order status: order count aur revenue (rounded). Columns: status, orders, revenue. Orders se utarte sorted.'],
        'SELECT o.status, COUNT(*) AS orders, ROUND(SUM(p.amount), 2) AS revenue\nFROM orders o JOIN payments p ON p.order_id = o.id\nGROUP BY o.status ORDER BY orders DESC;',
        undefined,
        [['Join, group the dimension, two aggregates.', 'Join karo, dimension group karo, do aggregates.'],
         ['SELECT o.status, COUNT(*) AS orders, ROUND(SUM(p.amount),2) AS revenue FROM orders o JOIN payments p ON p.order_id = o.id GROUP BY o.status ORDER BY orders DESC;', 'SELECT o.status, COUNT(*) AS orders, ROUND(SUM(p.amount),2) AS revenue FROM orders o JOIN payments p ON p.order_id = o.id GROUP BY o.status ORDER BY orders DESC;'],
         ['Pending and cancelled (105 each) lead by count.', 'Count me pending aur cancelled (105-105) aage.']],
        { ignoreRowOrder: false },
      ),
      t('task-4', 'medium',
        ['Marketing: is the VIP tier paying off?', 'Marketing: kya VIP tier paise vasool hai?'],
        ['VIP revenue only: total revenue from orders placed by VIP customers, rounded, aliased vip_revenue.', 'Sirf VIP revenue: VIP customers ke orders se total revenue, rounded, aliased vip_revenue.'],
        "SELECT ROUND(SUM(p.amount), 2) AS vip_revenue\nFROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\nWHERE c.customer_type = 'vip';",
        undefined,
        [['Filter the tier BEFORE aggregating — WHERE, not HAVING.', 'Aggregate se PEHLE tier filter karo — WHERE, HAVING nahi.'],
         ["SELECT ROUND(SUM(p.amount), 2) AS vip_revenue FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id WHERE c.customer_type = 'vip';", "SELECT ROUND(SUM(p.amount), 2) AS vip_revenue FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id WHERE c.customer_type = 'vip';"],
         ['15 VIPs generate a hefty share.', '15 VIPs bada hissa banate hain.']],
        { checkColumnNames: true },
      ),
      t('task-5', 'medium',
        ['The product league table.', 'Product league table.'],
        ['Top 5 products by total line revenue (SUM of order_items.subtotal) — name, revenue (rounded). Sorted by revenue descending.', 'Total line revenue se (order_items.subtotal ka SUM) top 5 products — name, revenue (rounded). Revenue se utarte sorted.'],
        'SELECT pr.name, ROUND(SUM(oi.subtotal), 2) AS revenue\nFROM order_items oi JOIN products pr ON pr.id = oi.product_id\nGROUP BY pr.id, pr.name ORDER BY revenue DESC LIMIT 5;',
        undefined,
        [['Product grain maths live in order_items — no payments join.', 'Product ka maths order_items me hai — payments join nahi.'],
         ['SELECT pr.name, ROUND(SUM(oi.subtotal),2) AS revenue FROM order_items oi JOIN products pr ON pr.id = oi.product_id GROUP BY pr.id, pr.name ORDER BY revenue DESC LIMIT 5;', 'SELECT pr.name, ROUND(SUM(oi.subtotal),2) AS revenue FROM order_items oi JOIN products pr ON pr.id = oi.product_id GROUP BY pr.id, pr.name ORDER BY revenue DESC LIMIT 5;'],
         ['Titan-family products crowd the top.', 'Titan-family products top par bhiDte hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-6', 'medium',
        ['The monthly pivot slide.', 'Monthly pivot slide.'],
        ['Per month: delivered count, cancelled count and delivered revenue (rounded). Columns: month, delivered, cancelled, revenue. Sorted by month.', 'Har mahine: delivered count, cancelled count aur delivered revenue (rounded). Columns: month, delivered, cancelled, revenue. Month se sorted.'],
        "SELECT substr(o.order_date, 1, 7) AS month,\n  SUM(CASE WHEN o.status = 'delivered' THEN 1 ELSE 0 END) AS delivered,\n  SUM(CASE WHEN o.status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled,\n  ROUND(SUM(CASE WHEN o.status = 'delivered' THEN p.amount ELSE 0 END), 2) AS revenue\nFROM orders o JOIN payments p ON p.order_id = o.id\nGROUP BY substr(o.order_date, 1, 7) ORDER BY month;",
        undefined,
        [['Three conditional aggregates at month grain.', 'Month grain par teen conditional aggregates.'],
         ["GROUP BY substr(o.order_date,1,7) with the CASE trio.", "GROUP BY substr(o.order_date,1,7) with the CASE trio."],
         ['Twelve rows, chart-ready.', 'Barah rows, chart-ready.']],
        { ignoreRowOrder: false },
      ),
      t('task-7', 'hard',
        ['The big spenders for the loyalty programme.', 'Loyalty programme ke liye big spenders.'],
        ['Customers whose total spend exceeds 800,000 — name and total (rounded). Columns: name, total. Sorted by total descending.', 'Jinka total kharch 8,00,000 paar — naam aur total (rounded). Columns: name, total. Total se utarte sorted.'],
        'SELECT c.name, ROUND(SUM(p.amount), 2) AS total\nFROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\nGROUP BY c.id, c.name HAVING SUM(p.amount) > 800000\nORDER BY total DESC;',
        undefined,
        [['Group per customer, gate with HAVING on the aggregate.', 'Per customer group karo, aggregate par HAVING se gate lagao.'],
         ['SELECT c.name, ROUND(SUM(p.amount),2) AS total FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id GROUP BY c.id, c.name HAVING SUM(p.amount) > 800000 ORDER BY total DESC;', 'SELECT c.name, ROUND(SUM(p.amount),2) AS total FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id GROUP BY c.id, c.name HAVING SUM(p.amount) > 800000 ORDER BY total DESC;'],
         ['Seven customers cross the line.', 'Saat customers lakeer paar karte hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-8', 'hard',
        ['Category depth for the merchandising review.', 'Merchandising review ke liye category depth.'],
        ['Parent categories (parent_category_id IS NULL) with total product-line revenue through their subcategories (self-join). Columns: name, revenue (rounded). Sorted by revenue descending.', 'Parent categories (parent_category_id IS NULL) apni subcategories se hote hue total product-line revenue ke saath (self-join). Columns: name, revenue (rounded). Revenue se utarte sorted.'],
        'SELECT parent.name, ROUND(SUM(oi.subtotal), 2) AS revenue\nFROM categories parent\nJOIN categories sub ON sub.parent_category_id = parent.id\nJOIN products pr ON pr.category_id = sub.id\nJOIN order_items oi ON oi.product_id = pr.id\nGROUP BY parent.id, parent.name\nORDER BY revenue DESC;',
        undefined,
        [['Four joins: parent→sub→products→order_items.', 'Chaar joins: parent→sub→products→order_items.'],
         ['SELECT parent.name, ROUND(SUM(oi.subtotal),2) AS revenue FROM categories parent JOIN categories sub ON sub.parent_category_id = parent.id JOIN products pr ON pr.category_id = sub.id JOIN order_items oi ON oi.product_id = pr.id GROUP BY parent.id, parent.name ORDER BY revenue DESC;', 'SELECT parent.name, ROUND(SUM(oi.subtotal),2) AS revenue FROM categories parent JOIN categories sub ON sub.parent_category_id = parent.id JOIN products pr ON pr.category_id = sub.id JOIN order_items oi ON oi.product_id = pr.id GROUP BY parent.id, parent.name ORDER BY revenue DESC;'],
         ['Five parent rows, one per top category.', 'Paanch parent rows, har top category ki ek.']],
        { ignoreRowOrder: false },
      ),
      t('task-9', 'very_hard',
        ['The benchmark report for the review.', 'Review ke liye benchmark report.'],
        ['Per customer tier: revenue and an above_average flag (1/0) marking tiers whose revenue exceeds the average tier revenue (CTE + subquery). Columns: customer_type, revenue, above_average. Sorted by customer_type.', 'Har customer tier: revenue aur above_average flag (1/0) jo bataye ki tier ki revenue average tier revenue se zyada hai (CTE + subquery). Columns: customer_type, revenue, above_average. customer_type se sorted.'],
        "WITH tier_revenue AS (\n  SELECT c.customer_type, SUM(p.amount) AS revenue\n  FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\n  GROUP BY c.customer_type\n)\nSELECT customer_type, ROUND(revenue, 2) AS revenue,\n  CASE WHEN revenue > (SELECT AVG(revenue) FROM tier_revenue) THEN 1 ELSE 0 END AS above_average\nFROM tier_revenue ORDER BY customer_type;",
        undefined,
        [['A CTE makes the self-comparison clean.', 'CTE self-comparison saaf rakhta hai.'],
         ['WITH tier_revenue AS (…) SELECT …, CASE WHEN revenue > (SELECT AVG(revenue) FROM tier_revenue) THEN 1 ELSE 0 END …;', 'WITH tier_revenue AS (…) SELECT …, CASE WHEN revenue > (SELECT AVG(revenue) FROM tier_revenue) THEN 1 ELSE 0 END …;'],
         ['One tier must sit above the mean.', 'Koi ek tier mean se upar hoga.']],
        { ignoreRowOrder: false },
      ),
      t('task-10', 'very_hard',
        ['The one-number KPI every slide quotes.', 'Wo ek-number KPI jo har slide quote karta hai.'],
        ['Average order value: total payments ÷ total orders, rounded to 2 decimals, aliased aov. One row.', 'Average order value: total payments ÷ total orders, 2 decimals par rounded, aliased aov. Ek row.'],
        'SELECT ROUND((SELECT SUM(amount) FROM payments) / (SELECT COUNT(*) FROM orders), 2) AS aov;',
        undefined,
        [['Two scalar subqueries, one division.', 'Do scalar subqueries, ek division.'],
         ['SELECT ROUND((SELECT SUM(amount) FROM payments) / (SELECT COUNT(*) FROM orders), 2) AS aov;', 'SELECT ROUND((SELECT SUM(amount) FROM payments) / (SELECT COUNT(*) FROM orders), 2) AS aov;'],
         ['≈ 75593.31.', '≈ 75593.31.']],
        { checkColumnNames: true },
      ),
    ],
  },
];

const PROJECTS_PART7: Project[] = [
  {
    id: 'lp3',
    kind: 'level',
    moduleNumber: 60,
    order: 9,
    title: { en: 'Dashboard Data Layer', hi: 'Dashboard Data Layer' },
    subtitle: { en: 'Eight production-grade queries powering a metrics dashboard', hi: 'Metrics dashboard chalane wali aath production-grade queries' },
    dataset: 'advanced',
    intro: {
      en: 'The dashboard team needs its data layer: every card on screen maps to one query here. Executive summary, pipeline, growth monitor, leaderboards, CLV, a reusable view, and the index that keeps it fast.',
      hi: 'Dashboard team ko apna data layer chahiye: screen ki har card ek query se judti hai. Executive summary, pipeline, growth monitor, leaderboards, CLV, reusable view, aur speed dene wala index.',
    },
    skillsTested: ['windows', 'CTE', 'views', 'indexes', 'CASE', 'LEFT JOIN'],
    estimatedTime: '75 min',
    tasks: [
      t('task-1', 'easy',
        ['The executive summary card.', 'Executive summary card.'],
        ['One row with three numbers: total revenue (revenue), total orders (orders), average order value (aov, rounded 2). Headers checked.', 'Ek row me teen numbers: total revenue (revenue), total orders (orders), average order value (aov, rounded 2). Headers check honge.'],
        'SELECT\n  ROUND(SUM(p.amount), 2) AS revenue,\n  COUNT(DISTINCT o.id) AS orders,\n  ROUND(SUM(p.amount) / COUNT(DISTINCT o.id), 2) AS aov\nFROM orders o JOIN payments p ON p.order_id = o.id;',
        undefined,
        [['One join, three aggregates, one row.', 'Ek join, teen aggregates, ek row.'],
         ['SELECT ROUND(SUM(p.amount),2) AS revenue, COUNT(DISTINCT o.id) AS orders, ROUND(SUM(p.amount)/COUNT(DISTINCT o.id),2) AS aov FROM orders o JOIN payments p ON p.order_id = o.id;', 'SELECT ROUND(SUM(p.amount),2) AS revenue, COUNT(DISTINCT o.id) AS orders, ROUND(SUM(p.amount)/COUNT(DISTINCT o.id),2) AS aov FROM orders o JOIN payments p ON p.order_id = o.id;'],
         ['≈ 51.5M revenue across 500 orders.', '500 orders par ≈ 51.5M revenue.']],
        { checkColumnNames: true },
      ),
      t('task-2', 'easy',
        ['The shipping pipeline card.', 'Shipping pipeline card.'],
        ['Shipping statuses with counts and RANK by volume. Columns: shipping_status, n, rnk. Sorted by rnk, shipping_status.', 'Shipping statuses counts aur RANK volume se. Columns: shipping_status, n, rnk. rnk, shipping_status se sorted.'],
        'SELECT shipping_status, COUNT(*) AS n,\n  RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk\nFROM shipping GROUP BY shipping_status ORDER BY rnk, shipping_status;',
        undefined,
        [['Group, then rank the grouped counts.', 'Group karo, phir grouped counts rank karo.'],
         ['SELECT shipping_status, COUNT(*) AS n, RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk FROM shipping GROUP BY shipping_status ORDER BY rnk, shipping_status;', 'SELECT shipping_status, COUNT(*) AS n, RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk FROM shipping GROUP BY shipping_status ORDER BY rnk, shipping_status;'],
         ['delivered (250) leads.', 'delivered (250) sabse aage.']],
        { ignoreRowOrder: false },
      ),
      t('task-3', 'medium',
        ['The growth monitor line.', 'Growth monitor line.'],
        ['Month, revenue (rounded) and month-over-month growth_pct (1 decimal) with a health flag — surge (≥ 20), dip (≤ −20), steady, start (first month). Columns: month, revenue, growth_pct, health. Sorted by month. LIMIT 12.', 'Month, revenue (rounded) aur month-over-month growth_pct (1 decimal) health flag ke saath — surge (≥ 20), dip (≤ −20), steady, start (pehla mahina). Columns: month, revenue, growth_pct, health. Month se sorted. LIMIT 12.'],
        "WITH monthly AS (\n  SELECT substr(o.order_date, 1, 7) AS month, SUM(p.amount) AS revenue\n  FROM orders o JOIN payments p ON p.order_id = o.id\n  GROUP BY substr(o.order_date, 1, 7)\n), growth AS (\n  SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev FROM monthly\n)\nSELECT month, ROUND(revenue, 2) AS revenue,\n  ROUND(100.0 * (revenue - prev) / prev, 1) AS growth_pct,\n  CASE WHEN prev IS NULL THEN 'start'\n       WHEN 100.0 * (revenue - prev) / prev >= 20 THEN 'surge'\n       WHEN 100.0 * (revenue - prev) / prev <= -20 THEN 'dip'\n       ELSE 'steady' END AS health\nFROM growth ORDER BY month LIMIT 12;",
        undefined,
        [['Three levels: sums → lag → flags; NULL-safe first month.', 'Teen level: sums → lag → flags; pehla mahina NULL-safe.'],
         ['The CASE reads the growth expression; thresholds 20 and −20.', 'CASE growth expression padhta hai; thresholds 20 aur −20.'],
         ['January is the start row by design.', 'January design se start row hai.']],
        { ignoreRowOrder: false },
      ),
      t('task-4', 'medium',
        ['The product leaderboard.', 'Product leaderboard.'],
        ['Products ranked by total line revenue with DENSE_RANK — name, revenue (rounded), drnk. Sorted by drnk, name. LIMIT 8.', 'Products total line revenue se DENSE_RANK ke saath — name, revenue (rounded), drnk. drnk, name se sorted. LIMIT 8.'],
        "WITH product_rev AS (\n  SELECT pr.name, SUM(oi.subtotal) AS revenue\n  FROM order_items oi JOIN products pr ON pr.id = oi.product_id\n  GROUP BY pr.id, pr.name\n)\nSELECT name, ROUND(revenue, 2) AS revenue,\n  DENSE_RANK() OVER (ORDER BY revenue DESC) AS drnk\nFROM product_rev ORDER BY drnk, name LIMIT 8;",
        undefined,
        [['Aggregate first; dense rank the aggregate.', 'Pehle aggregate; phir dense rank.'],
         ['WITH product_rev AS (…) SELECT name, ROUND(revenue,2), DENSE_RANK() OVER (ORDER BY revenue DESC) FROM product_rev ORDER BY 3, name LIMIT 8;', 'WITH product_rev AS (…) SELECT name, ROUND(revenue,2), DENSE_RANK() OVER (ORDER BY revenue DESC) FROM product_rev ORDER BY 3, name LIMIT 8;'],
         ['Ties share steps — extra rows at the top.', 'Ties steps share karti hain — upar extra rows.']],
        { ignoreRowOrder: false },
      ),
      t('task-5', 'hard',
        ['CLV — customer lifetime value.', 'CLV — customer lifetime value.'],
        ['Per customer: order count (orders_), lifetime spend (total, rounded) and aov (total ÷ orders_, rounded 2). Columns: name, orders_, total, aov. Sorted by total descending. LIMIT 8.', 'Har customer: order count (orders_), lifetime kharch (total, rounded) aur aov (total ÷ orders_, rounded 2). Columns: name, orders_, total, aov. Total se utarte sorted. LIMIT 8.'],
        "WITH cust AS (\n  SELECT c.name, COUNT(o.id) AS orders_, SUM(p.amount) AS total\n  FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\n  GROUP BY c.id, c.name\n)\nSELECT name, orders_, ROUND(total, 2) AS total, ROUND(total / orders_, 2) AS aov\nFROM cust ORDER BY total DESC LIMIT 8;",
        undefined,
        [['Pipeline first (counts + sums per customer), then the ratio column.', 'Pehle pipeline (per customer counts + sums), phir ratio column.'],
         ['aov = total / orders_ computed in the final SELECT over the CTE.', 'aov = total / orders_ final SELECT me CTE ke upar compute hota hai.'],
         ['Isha Verma tops CLV in this dataset.', 'Is dataset me Isha Verma CLV me sabse upar hai.']],
        { ignoreRowOrder: false },
      ),
      t('task-6', 'hard',
        ['The churn watchlist card.', 'Churn watchlist card.'],
        ['Customers whose last order is older than 2023-07-01 — name and last_order. Columns: name, last_order. Sorted by last_order, name. LIMIT 10.', 'Jinka aakhri order 2023-07-01 se purana — naam aur last_order. Columns: name, last_order. last_order, name se sorted. LIMIT 10.'],
        "WITH last_order AS (\n  SELECT c.name, MAX(o.order_date) AS last_order\n  FROM customers c JOIN orders o ON o.customer_id = c.id\n  GROUP BY c.id, c.name\n)\nSELECT name, last_order FROM last_order\nWHERE last_order < '2023-07-01'\nORDER BY last_order, name LIMIT 10;",
        undefined,
        [['MAX(order_date) per customer, then the threshold.', 'Per customer MAX(order_date), phir threshold.'],
         ["WHERE last_order < '2023-07-01' — the churn cutoff.", "WHERE last_order < '2023-07-01' — churn cutoff."],
         ['The at-risk list for retention.', 'Retention ke liye at-risk list.']],
        { ignoreRowOrder: false },
      ),
      t('task-7', 'very_hard',
        ['The reusable analytics view.', 'Reusable analytics view.'],
        ['CREATE VIEW v_monthly_revenue (month, revenue per month via the chain), then SELECT month, revenue from it sorted by month, LIMIT 6.', 'CREATE VIEW v_monthly_revenue (chain se monthly revenue), phir usse month, revenue padho month se sorted, LIMIT 6.'],
        "DROP VIEW IF EXISTS v_monthly_revenue;\nCREATE VIEW v_monthly_revenue AS\nSELECT substr(o.order_date, 1, 7) AS month, SUM(p.amount) AS revenue\nFROM orders o JOIN payments p ON p.order_id = o.id\nGROUP BY substr(o.order_date, 1, 7);\nSELECT month, revenue FROM v_monthly_revenue ORDER BY month LIMIT 6;",
        'SELECT month, revenue FROM v_monthly_revenue ORDER BY month LIMIT 6',
        [['The view body is the familiar pipeline; DROP IF EXISTS guards recreation.', 'View body wahi familiar pipeline hai; DROP IF EXISTS recreation bachata hai.'],
         ['Then read from the view like a table.', 'Phir view se table ki tarah padho.'],
         ['The BI asset other queries build on.', 'Wo BI asset jis par doosri queries banti hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-8', 'very_hard',
        ['The performance pack that keeps the dashboard fast.', 'Wo performance pack jo dashboard fast rakhta hai.'],
        ['CREATE INDEX idx_lp3_orders_cust_date ON orders(customer_id, order_date); EXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 7 ORDER BY order_date. Submit both — the composite index must appear in the plan.', 'CREATE INDEX idx_lp3_orders_cust_date ON orders(customer_id, order_date); EXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 7 ORDER BY order_date. Dono submit karo — composite index plan me dikhna chahiye.'],
        "CREATE INDEX idx_lp3_orders_cust_date ON orders(customer_id, order_date);\nEXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 7 ORDER BY order_date;",
        "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_lp3_orders_cust_date'",
        [['One composite, one verified plan — the deployable pair.', 'Ek composite, ek verified plan — deployable jodi.'],
         ['The composite serves the filter AND the sort together.', 'Composite filter AUR sort dono saath serve karta hai.'],
         ['The plan line proves it.', 'Plan line use saabit karti hai.']],
      ),
    ],
  },
];

const PROJECTS_PART8: Project[] = [
  {
    id: 'capstone',
    kind: 'capstone',
    moduleNumber: 60,
    order: 10,
    title: { en: '👑 Capstone: Business Intelligence System', hi: '👑 Capstone: Business Intelligence System' },
    subtitle: { en: 'Twelve deliverables that compose into one complete BI system', hi: 'Barah deliverables jo milkar ek poora BI system banate hain' },
    dataset: 'advanced',
    intro: {
      en: 'The final build: a complete BI layer over the full 10-table database. Value boards, growth monitors, rankings, CLV, region analysis, churn cohorts, a shipped view, the performance index, and the automation trigger — every pillar of the course in twelve deliverables.',
      hi: 'Aakhri build: poore 10-table database par poora BI layer. Value boards, growth monitors, rankings, CLV, region analysis, churn cohorts, ek shipped view, performance index, aur automation trigger — course ka har stambh barah deliverables me.',
    },
    skillsTested: ['everything', 'windows', 'CTE', 'views', 'indexes', 'triggers', 'CASE'],
    estimatedTime: '120 min',
    tasks: [
      t('task-1', 'very_hard',
        ['D1 — The value board.', 'D1 — Value board.'],
        ['Per-customer total spend with tiers: platinum (≥ 1,000,000), gold (≥ 500,000), else silver. Columns: name, total (rounded), tier. Sorted by total descending. LIMIT 10.', 'Per-customer total spend tiers ke saath: platinum (≥ 10,00,000), gold (≥ 5,00,000), warna silver. Columns: name, total (rounded), tier. Total se utarte sorted. LIMIT 10.'],
        "WITH spend AS (\n  SELECT c.name, SUM(p.amount) AS total\n  FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\n  GROUP BY c.id, c.name\n)\nSELECT name, ROUND(total, 2) AS total,\n  CASE WHEN total >= 1000000 THEN 'platinum' WHEN total >= 500000 THEN 'gold' ELSE 'silver' END AS tier\nFROM spend ORDER BY total DESC LIMIT 10;",
        undefined,
        [['Pipeline (spend) then business layer (CASE tiers).', 'Pehle pipeline (spend) phir business layer (CASE tiers).'],
         ['WITH spend AS (…) SELECT name, ROUND(total,2), CASE WHEN total >= 1000000 THEN … END FROM spend ORDER BY total DESC LIMIT 10;', 'WITH spend AS (…) SELECT name, ROUND(total,2), CASE WHEN total >= 1000000 THEN … END FROM spend ORDER BY total DESC LIMIT 10;'],
         ['Isha Verma leads the platinum tier.', 'Isha Verma platinum tier me sabse aage.']],
        { ignoreRowOrder: false },
      ),
      t('task-2', 'very_hard',
        ['D2 — The growth monitor.', 'D2 — Growth monitor.'],
        ['Month, revenue (rounded), growth_pct (1 decimal, NULL first month), health flag — surge ≥ 20, dip ≤ −20, steady, start. Columns: month, revenue, growth_pct, health. Sorted by month. LIMIT 12.', 'Month, revenue (rounded), growth_pct (1 decimal, pehle mahine ka NULL), health flag — surge ≥ 20, dip ≤ −20, steady, start. Columns: month, revenue, growth_pct, health. Month se sorted. LIMIT 12.'],
        "WITH monthly AS (\n  SELECT substr(o.order_date, 1, 7) AS month, SUM(p.amount) AS revenue\n  FROM orders o JOIN payments p ON p.order_id = o.id\n  GROUP BY substr(o.order_date, 1, 7)\n), growth AS (\n  SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev FROM monthly\n)\nSELECT month, ROUND(revenue, 2) AS revenue,\n  ROUND(100.0 * (revenue - prev) / prev, 1) AS growth_pct,\n  CASE WHEN prev IS NULL THEN 'start'\n       WHEN 100.0 * (revenue - prev) / prev >= 20 THEN 'surge'\n       WHEN 100.0 * (revenue - prev) / prev <= -20 THEN 'dip'\n       ELSE 'steady' END AS health\nFROM growth ORDER BY month LIMIT 12;",
        undefined,
        [['Three levels: sums → lag → flags.', 'Teen level: sums → lag → flags.'],
         ['NULL-safe first month; thresholds 20 and −20.', 'Pehla mahina NULL-safe; thresholds 20 aur −20.'],
         ['Twelve rows — the full year with health labels.', 'Barah rows — poora saal health labels ke saath.']],
        { ignoreRowOrder: false },
      ),
      t('task-3', 'hard',
        ['D3 — The product league.', 'D3 — Product league.'],
        ['Products ranked by total revenue (order_items.subtotal) with DENSE_RANK. Columns: name, revenue (rounded), drnk. Sorted by drnk, name. Top 10 only.', 'Products total revenue se (order_items.subtotal) DENSE_RANK ke saath ranked. Columns: name, revenue (rounded), drnk. drnk, name se sorted. Sirf top 10.'],
        "WITH product_rev AS (\n  SELECT pr.name, SUM(oi.subtotal) AS revenue\n  FROM order_items oi JOIN products pr ON pr.id = oi.product_id\n  GROUP BY pr.id, pr.name\n)\nSELECT name, ROUND(revenue, 2) AS revenue,\n  DENSE_RANK() OVER (ORDER BY revenue DESC) AS drnk\nFROM product_rev ORDER BY drnk, name LIMIT 10;",
        undefined,
        [['Aggregate first; dense rank the aggregate.', 'Pehle aggregate; phir dense rank.'],
         ['Product maths live in order_items — no payments join.', 'Product ka maths order_items me hai — payments join nahi.'],
         ['Ties share steps.', 'Ties steps share karti hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-4', 'medium',
        ['D4 — The shipped view.', 'D4 — Shipped view.'],
        ['CREATE VIEW v_monthly_revenue (month, revenue per month), then SELECT month, revenue from it sorted by month LIMIT 6. The BI asset.', 'CREATE VIEW v_monthly_revenue (monthly revenue), phir usse month, revenue padho month se sorted LIMIT 6. BI asset.'],
        "DROP VIEW IF EXISTS v_monthly_revenue;\nCREATE VIEW v_monthly_revenue AS\nSELECT substr(o.order_date, 1, 7) AS month, SUM(p.amount) AS revenue\nFROM orders o JOIN payments p ON p.order_id = o.id\nGROUP BY substr(o.order_date, 1, 7);\nSELECT month, revenue FROM v_monthly_revenue ORDER BY month LIMIT 6;",
        'SELECT month, revenue FROM v_monthly_revenue ORDER BY month LIMIT 6',
        [['The view body is the familiar pipeline.', 'View body wahi familiar pipeline hai.'],
         ['DROP VIEW IF EXISTS first, then CREATE, then SELECT.', 'Pehle DROP VIEW IF EXISTS, phir CREATE, phir SELECT.'],
         ['Reuse for every growth query.', 'Har growth query ke liye reuse.']],
        { ignoreRowOrder: false },
      ),
      t('task-5', 'very_hard',
        ['D5 — The churn watchlist.', 'D5 — Churn watchlist.'],
        ['Customers whose LAST order is older than 2023-07-01 — name and last_order. Columns: name, last_order. Sorted by last_order, name. LIMIT 10.', 'Jinka AAKHRI order 2023-07-01 se purana — naam aur last_order. Columns: name, last_order. last_order, name se sorted. LIMIT 10.'],
        "WITH last_order AS (\n  SELECT c.name, MAX(o.order_date) AS last_order\n  FROM customers c JOIN orders o ON o.customer_id = c.id\n  GROUP BY c.id, c.name\n)\nSELECT name, last_order FROM last_order\nWHERE last_order < '2023-07-01'\nORDER BY last_order, name LIMIT 10;",
        undefined,
        [['MAX(order_date) per customer, then the threshold — the churn pattern.', 'Per customer MAX(order_date), phir threshold — churn pattern.'],
         ['The cohort analysis for retention.', 'Retention ke liye cohort analysis.'],
         ['The at-risk list.', 'At-risk list.']],
        { ignoreRowOrder: false },
      ),
      t('task-6', 'very_hard',
        ['D6 — Segment champions.', 'D6 — Segment champions.'],
        ['The top spender PER segment (ROW_NUMBER partitioned by segment_name over the four-table chain). Columns: segment_name, name, spend (rounded). Sorted by segment_name.', 'HAR segment ka top spender (chaar-table chain par segment_name se partitioned ROW_NUMBER). Columns: segment_name, name, spend (rounded). segment_name se sorted.'],
        "SELECT segment_name, name, spend FROM (\n  SELECT cs.segment_name, c.name, ROUND(SUM(p.amount), 2) AS spend,\n    ROW_NUMBER() OVER (PARTITION BY cs.segment_name ORDER BY SUM(p.amount) DESC, c.id) AS rn\n  FROM customer_segments cs JOIN customers c ON c.id = cs.customer_id\n  JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\n  GROUP BY cs.segment_name, c.id, c.name\n) WHERE rn = 1 ORDER BY segment_name;",
        undefined,
        [['Top-1-per-group over the four-table chain.', 'Chaar-table chain par Top-1-per-group.'],
         ['ROW_NUMBER() OVER (PARTITION BY cs.segment_name ORDER BY SUM(p.amount) DESC, c.id).', 'ROW_NUMBER() OVER (PARTITION BY cs.segment_name ORDER BY SUM(p.amount) DESC, c.id).'],
         ['Six champions — one per segment.', 'Chah champions — har segment ka ek.']],
        { ignoreRowOrder: false },
      ),
      t('task-7', 'hard',
        ['D7 — The performance pack.', 'D7 — Performance pack.'],
        ['CREATE INDEX idx_cap_orders_cust_date ON orders(customer_id, order_date); EXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 7 ORDER BY order_date — the composite index must appear in the plan. Submit both.', 'CREATE INDEX idx_cap_orders_cust_date ON orders(customer_id, order_date); EXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 7 ORDER BY order_date — composite index plan me dikhna chahiye. Dono submit karo.'],
        "CREATE INDEX idx_cap_orders_cust_date ON orders(customer_id, order_date);\nEXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 7 ORDER BY order_date;",
        "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_cap_orders_cust_date'",
        [['One composite, one verified plan — the deployable pair.', 'Ek composite, ek verified plan — deployable jodi.'],
         ['The composite serves filter AND sort together.', 'Composite filter aur sort dono saath serve karta hai.'],
         ['The plan line proves it.', 'Plan line use saabit karti hai.']],
      ),
      t('task-8', 'very_hard',
        ['D8 — The automation trigger.', 'D8 — Automation trigger.'],
        ['CREATE TABLE cap_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, payment_id INTEGER, old_amount DECIMAL(10,2), new_amount DECIMAL(10,2), at DATETIME DEFAULT CURRENT_TIMESTAMP); CREATE TRIGGER trg_cap_audit AFTER UPDATE OF amount ON payments inserting both amounts; UPDATE payment 6 by +1; verify the audit row (payment_id, old_amount, new_amount).', 'CREATE TABLE cap_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, payment_id INTEGER, old_amount DECIMAL(10,2), new_amount DECIMAL(10,2), at DATETIME DEFAULT CURRENT_TIMESTAMP); CREATE TRIGGER trg_cap_audit AFTER UPDATE OF amount ON payments jo dono amounts dale; payment 6 ko +1 karo; audit row verify karo (payment_id, old_amount, new_amount).'],
        "CREATE TABLE IF NOT EXISTS cap_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, payment_id INTEGER, old_amount DECIMAL(10,2), new_amount DECIMAL(10,2), at DATETIME DEFAULT CURRENT_TIMESTAMP);\nCREATE TRIGGER trg_cap_audit AFTER UPDATE OF amount ON payments\nBEGIN\n  INSERT INTO cap_audit (payment_id, old_amount, new_amount) VALUES (OLD.id, OLD.amount, NEW.amount);\nEND;\nUPDATE payments SET amount = amount + 1 WHERE id = 6;\nSELECT payment_id, old_amount, new_amount FROM cap_audit WHERE payment_id = 6;",
        'SELECT payment_id, old_amount, new_amount FROM cap_audit WHERE payment_id = 6',
        [['Table, trigger, fire, verify — the graduation ritual.', 'Table, trigger, fire, verify — graduation ritual.'],
         ['OLD.amount before, NEW.amount after — one row of history.', 'OLD.amount pehle, NEW.amount baad — ek history row.'],
         ['The living BI system, automated.', 'Jeeta-jaagta BI system, automated.']],
      ),
      t('task-9', 'very_hard',
        ['D9 — Revenue by region.', 'D9 — Region-wise revenue.'],
        ['State-wise revenue with customer count — customers→orders→payments. Columns: state, revenue (rounded), customers (distinct). Sorted by revenue descending. LIMIT 10.', 'State ke hisab se revenue, customer count ke saath — customers→orders→payments. Columns: state, revenue (rounded), customers (distinct). Revenue se utarte sorted. LIMIT 10.'],
        "SELECT c.state, ROUND(SUM(p.amount), 2) AS revenue, COUNT(DISTINCT c.id) AS customers\nFROM customers c\nJOIN orders o ON o.customer_id = c.id\nJOIN payments p ON p.order_id = o.id\nGROUP BY c.state ORDER BY revenue DESC LIMIT 10;",
        undefined,
        [['Three tables, one group, two aggregates.', 'Teen tables, ek group, do aggregates.'],
         ['COUNT(DISTINCT c.id) counts unique buyers per state.', 'COUNT(DISTINCT c.id) har state ke unique buyers ginta hai.'],
         ['The big states lead.', 'Bade states aage hain.']],
        { ignoreRowOrder: false },
      ),
      t('task-10', 'very_hard',
        ['D10 — Customer Lifetime Value.', 'D10 — Customer Lifetime Value.'],
        ['Per customer: order count (orders_), lifetime spend (total, rounded) and aov (total ÷ orders_, rounded 2). Columns: name, orders_, total, aov. Sorted by total descending. LIMIT 8.', 'Har customer: order count (orders_), lifetime kharch (total, rounded) aur aov (total ÷ orders_, rounded 2). Columns: name, orders_, total, aov. Total se utarte sorted. LIMIT 8.'],
        "WITH cust AS (\n  SELECT c.name, COUNT(o.id) AS orders_, SUM(p.amount) AS total\n  FROM customers c JOIN orders o ON o.customer_id = c.id JOIN payments p ON p.order_id = o.id\n  GROUP BY c.id, c.name\n)\nSELECT name, orders_, ROUND(total, 2) AS total, ROUND(total / orders_, 2) AS aov\nFROM cust ORDER BY total DESC LIMIT 8;",
        undefined,
        [['Pipeline first (counts + sums), then the ratio.', 'Pehle pipeline (counts + sums), phir ratio.'],
         ['aov = total / orders_ in the final SELECT.', 'aov = total / orders_ final SELECT me.'],
         ['Isha Verma tops CLV.', 'Isha Verma CLV me sabse upar.']],
        { ignoreRowOrder: false },
      ),
      t('task-11', 'hard',
        ['D11 — Inventory movement.', 'D11 — Inventory movement.'],
        ['The 12 most recent inventory entries (id descending) with running totals of change_quantity. Columns: id, change_quantity, running_total. Sorted by id descending.', '12 sabse naye inventory entries (id se utarte) change_quantity ke running totals ke saath. Columns: id, change_quantity, running_total. Id se utarte sorted.'],
        "SELECT id, change_quantity, running_total FROM (\n  SELECT id, change_quantity,\n    SUM(change_quantity) OVER (ORDER BY id) AS running_total\n  FROM inventory_log\n) ORDER BY id DESC LIMIT 12;",
        undefined,
        [['The window ORDER BY defines "running"; the outer ORDER flips display.', 'Window ka ORDER BY "running" define karta hai; bahar ka ORDER display ulta karta hai.'],
         ['SUM(change_quantity) OVER (ORDER BY id) — the cumulative frame.', 'SUM(change_quantity) OVER (ORDER BY id) — cumulative frame.'],
         ['The top row (latest id) shows the final net position.', 'Sabse upar wali row (latest id) final net position dikhati hai.']],
        { ignoreRowOrder: false },
      ),
      t('task-12', 'very_hard',
        ['D12 — The executive dashboard row.', 'D12 — Executive dashboard row.'],
        ['ONE row with five KPIs — revenue, orders, aov, delivered, buyers (all rounded where money). Headers checked.', 'EK row me paanch KPIs — revenue, orders, aov, delivered, buyers (jahan paisa wahan rounded). Headers check honge.'],
        "SELECT\n  ROUND(SUM(p.amount), 2) AS revenue,\n  COUNT(DISTINCT o.id) AS orders,\n  ROUND(SUM(p.amount) / COUNT(DISTINCT o.id), 2) AS aov,\n  SUM(CASE WHEN o.status = 'delivered' THEN 1 ELSE 0 END) AS delivered,\n  COUNT(DISTINCT o.customer_id) AS buyers\nFROM orders o JOIN payments p ON p.order_id = o.id;",
        undefined,
        [['One join, five aggregates, one row — the CEO slide.', 'Ek join, paanch aggregates, ek row — CEO slide.'],
         ["The delivered KPI uses the conditional-count idiom.", "Delivered KPI conditional-count idiom use karta hai."],
         ['Expected shape: ≈ 51.5M revenue, 500 orders, ≈ 103K aov, 100 delivered, 65 buyers.', 'Expected shape: ≈ 51.5M revenue, 500 orders, ≈ 103K aov, 100 delivered, 65 buyers.']],
        { checkColumnNames: true },
      ),
    ],
  },
];

export const ALL_PROJECTS: Project[] = [...PROJECTS, ...PROJECTS_PART2, ...PROJECTS_PART3, ...PROJECTS_PART4, ...PROJECTS_PART5, ...PROJECTS_PART6, ...PROJECTS_PART7, ...PROJECTS_PART8];
